# Generated by Django 4.2.8 on 2024-02-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egowagtailmenus', '0003_alter_menu_slug_alter_menuitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egowagtailmenus.menuitem'),
        ),
    ]
