# Generated by Django 4.2.8 on 2024-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egowagtailmenus', '0004_alter_menu_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extra_class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra class'),
        ),
    ]
