# Generated by Django 4.2.8 on 2024-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('egowagtailmenus', '0005_menuitem_description_menuitem_extra_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
