
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-23T18:18:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2498a517ec989f74eb3ef1668a1563a535f67749",
 "version": "5.4.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
