/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ;
typedef struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA tySequence__UrPRVZYp6MbnOWXK4N9bUkA;
typedef struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content;
typedef struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ tySequence__owY9b1no7B0PqDQ8zV5DrxQ;
typedef struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_point__MN7UdrA9cGABfr4tCur5RbQ tyObject_point__MN7UdrA9cGABfr4tCur5RbQ;
typedef struct tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g;
typedef struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ tySequence__7s5HyddQ0f9bxMNILHrXwJQ;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw_Content tySequence__2ALwPJKv8Nz8mMm4Hy9crdw_Content;
typedef struct tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A;
typedef struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ;
typedef struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content;
typedef struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g tyTuple__kuMQ1fbjJlHtwKTmBGAe6g;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ {
	NI a;
	NI b;
};
struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA {
  NI len; tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content* p;
};
struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ {
  NI len; tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content* p;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_point__MN7UdrA9cGABfr4tCur5RbQ {
	NI16 x;
	NI16 y;
};
typedef NU8 tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw;
struct tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA {
	NU8 version;
	tySequence__UrPRVZYp6MbnOWXK4N9bUkA components;
	tySequence__owY9b1no7B0PqDQ8zV5DrxQ wires;
	NI save_id;
	NU32 hub_id;
	NimStringV2 hub_description;
	NI gate;
	NI delay;
	NIM_BOOL menu_visible;
	NU32 clock_speed;
	tySequence__qwqHTkRvwhrRyENtudHQ7g dependencies;
	NimStringV2 description;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ camera_position;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ player_data;
	tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw synced;
	NIM_BOOL campaign_bound;
};
typedef NU16 tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ;
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ {
  NI len; tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content* p;
};
struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA {
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ data;
	NI counter;
};
struct tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g {
	tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ kind;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ position;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ custom_displacement;
	NU8 rotation;
	NI8 real_offset;
	NI permanent_id;
	NimStringV2 custom_string;
	NI custom_id;
	NU64 setting1;
	NU64 setting2;
	tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA selected_programs;
	NI16 ui_order;
};
typedef tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ tyArray__hBeU0ADrQ9anu9czqQRkT8rA[5];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  NI len; tySequence__2ALwPJKv8Nz8mMm4Hy9crdw_Content* p;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw trace;
	Exception* up;
};
typedef tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ tyArray__A6gSbShB9a0ukUzbfLjetrw[3];
typedef NU8 tySet_tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ[33];
struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ {
  NI len; tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content* p;
};
typedef NU8 tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw;
struct tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A {
	tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ path;
	tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw kind;
	NU8 color;
	NimStringV2 comment;
};
typedef tyObject_point__MN7UdrA9cGABfr4tCur5RbQ tyArray__UfdIMDE1tgdULaKrSRVsiw[8];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content { NI cap; tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g data[SEQ_DECL_SIZE]; };
struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content { NI cap; tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g {
NI Field0;
NI Field1;
NimStringV2 Field2;
};
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content { NI cap; tyTuple__kuMQ1fbjJlHtwKTmBGAe6g data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw_Content { NI cap; tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE]; };
struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content { NI cap; tyObject_point__MN7UdrA9cGABfr4tCur5RbQ data[SEQ_DECL_SIZE]; };
static N_INLINE(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, uncompress__librariesZsupersnappyZsupersnappy_u523)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, eqdup___pureZtimes_u2540)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0);
static N_INLINE(NimStringV2, uncompress__librariesZsupersnappyZsupersnappy_u520)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, uncompress__librariesZsupersnappyZsupersnappy_u18)(NimStringV2* dst_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4581)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, X5BX5D___versionsZv50_u1485)(NU8* s_p0, NI s_p0Len_0, tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ x_p1);
static N_INLINE(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ, dotdot___stdZenumutils_u141)(NI a_p0, NI b_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0);
N_LIB_PRIVATE N_NIMCALL(NI, get_int__common_u377)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, get_bool__common_u369)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, get_u32__common_u421)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___common_u855)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, get_seq_int__common_u523)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZassertions_u36)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, get_string__common_u558)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, get_point__common_u504)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, get_seq_u8__common_u508)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL bits32_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2543)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___versionsZv48_u484)(tySequence__UrPRVZYp6MbnOWXK4N9bUkA* dest_p0, tySequence__UrPRVZYp6MbnOWXK4N9bUkA src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__UrPRVZYp6MbnOWXK4N9bUkA, get_components__versionsZv50_u1402)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL solution_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, get_component__versionsZv50_u6)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL solution_p2, tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* Result);
N_LIB_PRIVATE N_NIMCALL(NU16, get_u16__common_u445)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NI, find__versionsZv48_u65)(tyArray__hBeU0ADrQ9anu9czqQRkT8rA a_p0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u171)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NU8, get_u8__common_u465)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NU64, get_u64__common_u417)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
static N_INLINE(NIM_BOOL, contains__versionsZv48_u229)(tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ* a_p0, NI a_p0Len_0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1);
static N_INLINE(NI, find__versionsZv48_u234)(tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ* a_p0, NI a_p0Len_0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___versionsZv50_u115)(tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA* t_p0, NI key_p1, NimStringV2 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___versionsZv48_u289)(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__versionsZv48_u359)(tySequence__UrPRVZYp6MbnOWXK4N9bUkA* x_p0, tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___versionsZv48_u286)(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___versionsZv48_u644)(tySequence__owY9b1no7B0PqDQ8zV5DrxQ* dest_p0, tySequence__owY9b1no7B0PqDQ8zV5DrxQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__owY9b1no7B0PqDQ8zV5DrxQ, get_wires__versionsZv50_u1457)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__versionsZv48_u417)(tySequence__owY9b1no7B0PqDQ8zV5DrxQ* x_p0, tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, get_wire__versionsZv50_u1426)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* Result);
N_LIB_PRIVATE N_NIMCALL(void, add__versionsZv48_u16)(tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ* x_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, plus___common_u337)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ b_p1);
static N_INLINE(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ*, X5BX5D___versionsZv49_u141)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ* s_p0, NI s_p0Len_0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2534)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static NIM_CONST tySet_tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ TM__ljGBfV9aQQCwmridcrm4PoA_10 = {
0x00, 0x00, 0x78, 0x00, 0x00, 0x06, 0x20, 0x06,
0x0c, 0x00, 0x08, 0x08, 0x00, 0x00, 0x00, 0x00,
0x1f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00}
;
static NIM_CONST tyArray__hBeU0ADrQ9anu9czqQRkT8rA TM__ljGBfV9aQQCwmridcrm4PoA_5 = {((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)128),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)129),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)130),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)131),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)132)}
;
static NIM_CONST tyArray__hBeU0ADrQ9anu9czqQRkT8rA TM__ljGBfV9aQQCwmridcrm4PoA_6 = {((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)248),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)250),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)252),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)254),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)256)}
;
static NIM_CONST tyArray__A6gSbShB9a0ukUzbfLjetrw TM__ljGBfV9aQQCwmridcrm4PoA_9 = {((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)64),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)68),
((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)94)}
;
N_LIB_PRIVATE NIM_CONST tyArray__UfdIMDE1tgdULaKrSRVsiw DIRECTIONS__versionsZv50_u5 = {{((NI16)1), ((NI16)0)}
,
{((NI16)1), ((NI16)1)}
,
{((NI16)0), ((NI16)1)}
,
{((NI16)-1), ((NI16)1)}
,
{((NI16)-1), ((NI16)0)}
,
{((NI16)-1), ((NI16)-1)}
,
{((NI16)0), ((NI16)-1)}
,
{((NI16)1), ((NI16)-1)}
}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4363;
extern NIM_THREADVAR TFrame* framePtr__system_u3980;
extern NIM_THREADVAR Exception* currException__system_u3982;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4363);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3980 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3980).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3980;
	framePtr__system_u3980 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4581();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3980 = (*framePtr__system_u3980).prev;
}
static N_INLINE(NimStringV2, uncompress__librariesZsupersnappyZsupersnappy_u520)(NimStringV2 src_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("uncompress", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\libraries\\supersnappy\\supersnappy.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(143);
	uncompress__librariesZsupersnappyZsupersnappy_u18((&result), src_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, uncompress__librariesZsupersnappyZsupersnappy_u523)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
	NimStringV2 colontmpD__2;
NIM_BOOL* nimErr_;
	nimfr_("uncompress", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\libraries\\supersnappy\\supersnappy.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(147);
	nimlf_(1769, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\pure\\times.nim");
	nimlf_(147, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\libraries\\supersnappy\\supersnappy.nim");
	colontmpD__2 = uncompress__librariesZsupersnappyZsupersnappy_u520((*(NimStringV2*) (&src_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(1769, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\pure\\times.nim");
	colontmpD_ = eqdup___pureZtimes_u2540((*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&colontmpD__2)));
	result = colontmpD_;
	{
		LA1_:;
	}
	{
		nimlf_(370, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ, dotdot___stdZenumutils_u141)(NI a_p0, NI b_p1) {
	tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ result;
	nimfr_("..", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ));
	nimln_(416);
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ));
	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, find__versionsZv48_u65)(tyArray__hBeU0ADrQ9anu9czqQRkT8rA a_p0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1) {
	NI result;
	nimfr_("find", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
{	result = (NI)0;
	nimln_(1665);
	result = ((NI)0);
	{
		tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ i;
		NI i_2;
		i = (tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)0;
		nimlf_(38, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i_2 = ((NI)0);
		{
			nimln_(39);
			while (1) {
				NI TM__ljGBfV9aQQCwmridcrm4PoA_3;
				NI TM__ljGBfV9aQQCwmridcrm4PoA_4;
				nimlf_(1666, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
				i = a_p0[(i_2)- 0];
				{
					nimln_(1667);
					if (!(i == item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1666);
				if (nimAddInt(result, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_3);
				nimlf_(41, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				{
					if (!(((NI)4) <= ((NI) (i_2)))) goto LA10_;
					goto LA2;
				}
LA10_: ;
				nimln_(42);
				if (nimAddInt(i_2, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_4)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__ljGBfV9aQQCwmridcrm4PoA_4 < 0 || TM__ljGBfV9aQQCwmridcrm4PoA_4 > 4){ raiseOverflow(); goto BeforeRet_;
				}
				i_2 = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_4);
			}
		} LA2: ;
	}
	nimlf_(1669, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u171(&currException__system_u3982, (*currException__system_u3982).up, NIM_FALSE);
}
static N_INLINE(NI, find__versionsZv48_u234)(tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ* a_p0, NI a_p0Len_0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1) {
	NI result;
	nimfr_("find", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
{	result = (NI)0;
	nimln_(1665);
	result = ((NI)0);
	{
		tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ* i;
		NI i_2;
		i = (tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ*)0;
		nimlf_(13, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i_2 = ((NI)0);
		{
			nimln_(14);
			while (1) {
				NI TM__ljGBfV9aQQCwmridcrm4PoA_7;
				NI TM__ljGBfV9aQQCwmridcrm4PoA_8;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1666, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i = (&a_p0[i_2]);
				{
					nimln_(1667);
					if (!((*i) == item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1666);
				if (nimAddInt(result, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_7)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_7);
				nimlf_(16, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				if (nimAddInt(i_2, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_8)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_8);
			} LA3: ;
		}
	}
	nimlf_(1669, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__versionsZv48_u229)(tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ* a_p0, NI a_p0Len_0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
{	result = (NIM_BOOL)0;
	nimln_(1683);
	nimln_(1671);
	nimln_(1683);
	T1_ = (NI)0;
	T1_ = find__versionsZv48_u234(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, get_component__versionsZv50_u6)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL solution_p2, tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* Result) {
	tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ kind;
	NU16 T2_;
	NI index;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T16_;
	NU8 T17_;
	NI T18_;
	NimStringV2 T19_;
	NU64 T20_;
	NU64 T21_;
NIM_BOOL* nimErr_;
	nimfr_("get_component", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g));
	nimln_(19);
	T2_ = (NU16)0;
	T2_ = get_u16__common_u445(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if ((((NI) (T2_))) < ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)0) || (((NI) (T2_))) > ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)257)){ raiseRangeErrorI(((NI) (T2_)), ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)0), ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)257)); goto LA1_;
	}
	kind = ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ) (((NI) (T2_))));
	nimln_(20);
	index = find__versionsZv48_u65(TM__ljGBfV9aQQCwmridcrm4PoA_5, kind);
	nimln_(21);
	{
		if (!!((index == ((NI)-1)))) goto LA5_;
		nimln_(22);
		if ((NU)(index) > (NU)(4)){ raiseIndexError2(index, 4); goto LA1_;
		}
		kind = TM__ljGBfV9aQQCwmridcrm4PoA_6[(index)- 0];
	}
LA5_: ;
	nimln_(23);
	nimZeroMem((void*)Result, sizeof(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g));
	(*Result).kind = kind;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		{
			*nimErr_ = NIM_FALSE;
			popCurrentException();
			LA8_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(25);
	{
		NIM_BOOL T12_;
		T12_ = (NIM_BOOL)0;
		T12_ = solution_p2;
		if (!(T12_)) goto LA13_;
		T12_ = ((*Result).kind == ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)206));
LA13_: ;
		if (!T12_) goto LA14_;
		nimln_(26);
		(*Result).kind = ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)208);
	}
LA14_: ;
	nimln_(27);
	nimZeroMem((void*)(&T16_), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	T16_ = get_point__common_u504(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).position = T16_;
	nimln_(28);
	T17_ = (NU8)0;
	T17_ = get_u8__common_u465(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).rotation = T17_;
	nimln_(29);
	T18_ = (NI)0;
	T18_ = get_int__common_u377(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).permanent_id = T18_;
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	nimlf_(30, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T19_.len = 0; T19_.p = NIM_NIL;
	T19_ = get_string__common_u558(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u36((&(*Result).custom_string), T19_);
	nimlf_(31, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T20_ = (NU64)0;
	T20_ = get_u64__common_u417(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).setting1 = T20_;
	nimln_(32);
	T21_ = (NU64)0;
	T21_ = get_u64__common_u417(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).setting2 = T21_;
	nimln_(34);
	{
		NI T26_;
		tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T27_;
		if (!((*Result).kind == ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)92))) goto LA24_;
		nimln_(35);
		T26_ = (NI)0;
		T26_ = get_int__common_u377(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*Result).custom_id = T26_;
		nimln_(36);
		nimZeroMem((void*)(&T27_), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
		T27_ = get_point__common_u504(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*Result).custom_displacement = T27_;
	}
	goto LA22_;
LA24_: ;
	{
		NIM_BOOL T29_;
		NU16 len;
		NU16 T32_;
		NU16 j;
		nimln_(38);
		T29_ = (NIM_BOOL)0;
		T29_ = contains__versionsZv48_u229(TM__ljGBfV9aQQCwmridcrm4PoA_9, 3, (*Result).kind);
		if (!T29_) goto LA30_;
		nimln_(39);
		T32_ = (NU16)0;
		T32_ = get_u16__common_u445(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		len = T32_;
		nimln_(40);
		j = ((NU16)0);
		{
			nimln_(41);
			while (1) {
				NI key;
				NI T35_;
				NimStringV2 T36_;
				if (!((NU16)(j) < (NU16)(len))) goto LA34;
				nimln_(42);
				T35_ = (NI)0;
				T35_ = get_int__common_u377(input_p0, i_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				key = T35_;
				nimln_(43);
				T36_.len = 0; T36_.p = NIM_NIL;
				T36_ = get_string__common_u558(input_p0, i_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				X5BX5Deq___versionsZv50_u115((&(*Result).selected_programs), key, T36_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(44);
				j += ((NI)1);
			} LA34: ;
		}
	}
	goto LA22_;
LA30_: ;
LA22_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__UrPRVZYp6MbnOWXK4N9bUkA, get_components__versionsZv50_u1402)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL solution_p2) {
	tySequence__UrPRVZYp6MbnOWXK4N9bUkA result;
	NI len;
NIM_BOOL oldNimErrFin5_;
NIM_BOOL* nimErr_;
	nimfr_("get_components", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(47);
	len = get_int__common_u377(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI j;
		NI colontmp_;
		NI TM__ljGBfV9aQQCwmridcrm4PoA_2;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(75, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
		nimlf_(48, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
		if (nimSubInt(len, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_2);
		nimlf_(90, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
		res = ((NI)0);
		{
			nimln_(91);
			while (1) {
				NI TM__ljGBfV9aQQCwmridcrm4PoA_11;
				if (!(res <= colontmp_)) goto LA3;
				nimlf_(48, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
				j = res;
				{
					tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g comp;
					tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g blitTmp;
					nimZeroMem((void*)(&comp), sizeof(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g));
					nimln_(49);
					get_component__versionsZv50_u6(input_p0, i_p1, solution_p2, (&comp));
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					nimln_(50);
					{
						NIM_BOOL T8_;
						T8_ = (NIM_BOOL)0;
						T8_ = (comp.kind == ((tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ)0));
						if (T8_) goto LA9_;
						T8_ = ((TM__ljGBfV9aQQCwmridcrm4PoA_10[(NU)((comp.kind))>>3] &(1U<<((NU)((comp.kind))&7U)))!=0);
LA9_: ;
						if (!T8_) goto LA10_;
						nimlf_(30, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
						eqdestroy___versionsZv48_u289((&comp));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimlf_(50, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
						goto LA4;
					}
LA10_: ;
					nimln_(51);
					nimZeroMem((void*)(&blitTmp), sizeof(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g));
					blitTmp = comp;
					nimlf_(30, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
					eqwasMoved___versionsZv48_u286((&comp));
					nimlf_(51, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
					add__versionsZv48_u359((&result), (&blitTmp));
					{
						LA5_:;
					}
					{
						oldNimErrFin5_ = *nimErr_; *nimErr_ = NIM_FALSE;
						nimlf_(30, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
						eqdestroy___versionsZv48_u289((&comp));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						*nimErr_ = oldNimErrFin5_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA4: ;
				nimlf_(93, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
				if (nimAddInt(res, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_11)) { raiseOverflow(); goto BeforeRet_;
				};
				res = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_11);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ*, X5BX5D___versionsZv49_u141)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ* s_p0, NI s_p0Len_0, NI i_p1) {
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ* result;
	NI TM__ljGBfV9aQQCwmridcrm4PoA_13;
	nimfr_("[]", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\indices.nim");
{	result = (tyObject_point__MN7UdrA9cGABfr4tCur5RbQ*)0;
	nimln_(30);
	if (nimSubInt(s_p0Len_0, i_p1, &TM__ljGBfV9aQQCwmridcrm4PoA_13)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__ljGBfV9aQQCwmridcrm4PoA_13) < 0 || (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_13) >= s_p0Len_0){ raiseIndexError2((NI)(TM__ljGBfV9aQQCwmridcrm4PoA_13),s_p0Len_0-1); goto BeforeRet_;
	}
	result = (&s_p0[(NI)(TM__ljGBfV9aQQCwmridcrm4PoA_13)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, get_wire__versionsZv50_u1426)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* Result) {
	NU8 T1_;
	NU8 T2_;
	NimStringV2 T3_;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T4_;
	NU8 segment;
	NI length_left;
NIM_BOOL* nimErr_;
	nimfr_("get_wire", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A));
	nimln_(54);
	T1_ = (NU8)0;
	T1_ = get_u8__common_u465(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((T1_) < ((tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw)0) || (T1_) > ((tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw)4)){ raiseRangeErrorI(T1_, ((tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw)0), ((tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw)4)); goto BeforeRet_;
	}
	(*Result).kind = ((tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw) (T1_));
	nimln_(55);
	T2_ = (NU8)0;
	T2_ = get_u8__common_u465(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).color = T2_;
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	nimlf_(56, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = get_string__common_u558(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u36((&(*Result).comment), T3_);
	nimlf_(65, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T4_ = get_point__common_u504(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__versionsZv48_u16((&(*Result).path), T4_);
	nimln_(67);
	segment = get_u8__common_u465(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(70);
	{
		tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T9_;
		if (!(segment == ((NU8)32))) goto LA7_;
		nimln_(71);
		T9_ = get_point__common_u504(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		add__versionsZv48_u16((&(*Result).path), T9_);
		nimln_(72);
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(74);
	length_left = ((NI) ((NU8)(segment & ((NU8)31))));
	{
		nimln_(75);
		while (1) {
			tyObject_point__MN7UdrA9cGABfr4tCur5RbQ direction;
			if (!!((length_left == ((NI)0)))) goto LA11;
			nimln_(76);
			if ((NU)((NU8)((NU8)(segment) >> (NU64)(((NI)5)))) > (NU)(7)){ raiseIndexError2((NU8)((NU8)(segment) >> (NU64)(((NI)5))), 7); goto BeforeRet_;
			}
			direction = DIRECTIONS__versionsZv50_u5[((NU8)((NU8)(segment) >> (NU64)(((NI)5))))- 0];
			{
				nimln_(78);
				while (1) {
					tyObject_point__MN7UdrA9cGABfr4tCur5RbQ* T14_;
					tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T15_;
					NI TM__ljGBfV9aQQCwmridcrm4PoA_14;
					if (!(((NI)0) < length_left)) goto LA13;
					nimln_(79);
					T14_ = (tyObject_point__MN7UdrA9cGABfr4tCur5RbQ*)0;
					T14_ = X5BX5D___versionsZv49_u141((((*Result).path).p) ? ((*Result).path.p->data) : NIM_NIL, (*Result).path.len, ((NI)1));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T15_ = plus___common_u337((*T14_), direction);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					add__versionsZv48_u16((&(*Result).path), T15_);
					nimln_(80);
					if (nimSubInt(length_left, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_14)) { raiseOverflow(); goto BeforeRet_;
					};
					length_left = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_14);
				} LA13: ;
			}
			nimln_(82);
			segment = get_u8__common_u465(input_p0, i_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(83);
			length_left = ((NI) ((NU8)(segment & ((NU8)31))));
		} LA11: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__owY9b1no7B0PqDQ8zV5DrxQ, get_wires__versionsZv50_u1457)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	tySequence__owY9b1no7B0PqDQ8zV5DrxQ result;
	NI len;
NIM_BOOL* nimErr_;
	nimfr_("get_wires", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(86);
	len = get_int__common_u377(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI j;
		NI colontmp_;
		NI TM__ljGBfV9aQQCwmridcrm4PoA_12;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(75, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
		nimlf_(87, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
		if (nimSubInt(len, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_12)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_12);
		nimlf_(90, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
		res = ((NI)0);
		{
			nimln_(91);
			while (1) {
				tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A T4_;
				NI TM__ljGBfV9aQQCwmridcrm4PoA_15;
				if (!(res <= colontmp_)) goto LA3;
				nimlf_(87, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
				j = res;
				nimZeroMem((void*)(&T4_), sizeof(tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A));
				get_wire__versionsZv50_u1426(input_p0, i_p1, (&T4_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				add__versionsZv48_u417((&result), (&T4_));
				nimlf_(93, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators_1.nim");
				if (nimAddInt(res, ((NI)1), &TM__ljGBfV9aQQCwmridcrm4PoA_15)) { raiseOverflow(); goto BeforeRet_;
				};
				res = (NI)(TM__ljGBfV9aQQCwmridcrm4PoA_15);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, parse__versionsZv50_u1471)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ compressed_p0, NIM_BOOL headers_only_p1, NIM_BOOL solution_p2, tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA* parse_result_p3) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__2;
	tyObject_HSlice__radnDaA9aYYmhYW0ZEip9ctQ T2_;
	NI i;
	NI T3_;
	NI T4_;
	NI T5_;
	NIM_BOOL T6_;
	NU32 T7_;
	tySequence__qwqHTkRvwhrRyENtudHQ7g T8_;
	NimStringV2 T9_;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T10_;
	NIM_BOOL T11_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T12_;
NIM_BOOL* nimErr_;
	nimfr_("parse", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
{nimErr_ = nimErrorFlag();
	bytes.len = 0; bytes.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(91);
	T2_ = dotdot___stdZenumutils_u141(((NI)1), ((NI)1));
	colontmpD_ = X5BX5D___versionsZv50_u1485(((compressed_p0).p) ? (compressed_p0.p->data) : NIM_NIL, compressed_p0.len, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	bytes = uncompress__librariesZsupersnappyZsupersnappy_u523(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(92);
	i = ((NI)0);
	nimln_(94);
	T3_ = (NI)0;
	T3_ = rand__pureZrandom_u143(((NI)IL64(9223372036854775807)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).save_id = T3_;
	nimln_(95);
	T4_ = (NI)0;
	T4_ = get_int__common_u377(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).gate = T4_;
	nimln_(96);
	T5_ = (NI)0;
	T5_ = get_int__common_u377(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).delay = T5_;
	nimln_(97);
	T6_ = (NIM_BOOL)0;
	T6_ = get_bool__common_u369(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).menu_visible = T6_;
	nimln_(98);
	T7_ = (NU32)0;
	T7_ = get_u32__common_u421(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).clock_speed = T7_;
	nimlf_(525, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	nimlf_(99, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T8_.len = 0; T8_.p = NIM_NIL;
	T8_ = get_seq_int__common_u523(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(525, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	eqsink___common_u855((&(*parse_result_p3).dependencies), T8_);
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	nimlf_(100, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T9_.len = 0; T9_.p = NIM_NIL;
	T9_ = get_string__common_u558(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(25, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\std\\assertions.nim");
	eqsink___stdZassertions_u36((&(*parse_result_p3).description), T9_);
	nimlf_(101, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	nimZeroMem((void*)(&T10_), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	T10_ = get_point__common_u504(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*parse_result_p3).camera_position = T10_;
	nimln_(102);
	T11_ = (NIM_BOOL)0;
	T11_ = get_bool__common_u369(bytes, (&i));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(void)(T11_);
	nimln_(103);
	colontmpD__2 = get_seq_u8__common_u508(bytes, (&i), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(void)(colontmpD__2);
	nimlf_(1769, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\pure\\times.nim");
	nimlf_(104, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	T12_.len = 0; T12_.p = NIM_NIL;
	T12_ = get_seq_u8__common_u508(bytes, (&i), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(1769, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\pure\\times.nim");
	eqsink___pureZtimes_u2543((&(*parse_result_p3).player_data), T12_);
	nimlf_(106, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
	{
		tySequence__UrPRVZYp6MbnOWXK4N9bUkA T17_;
		tySequence__owY9b1no7B0PqDQ8zV5DrxQ T18_;
		if (!!(headers_only_p1)) goto LA15_;
		nimlf_(73, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
		nimlf_(107, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
		T17_.len = 0; T17_.p = NIM_NIL;
		T17_ = get_components__versionsZv50_u1402(bytes, (&i), solution_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(73, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
		eqsink___versionsZv48_u484((&(*parse_result_p3).components), T17_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(74);
		nimlf_(108, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v2.nim");
		T18_.len = 0; T18_.p = NIM_NIL;
		T18_ = get_wires__versionsZv50_u1457(bytes, (&i));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(74, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\versions\\v0.nim");
		eqsink___versionsZv48_u644((&(*parse_result_p3).wires), T18_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA15_: ;
	{
		LA1_:;
	}
	{
		nimlf_(1769, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\pure\\times.nim");
		eqdestroy___pureZtimes_u2534(colontmpD__2);
		eqdestroy___pureZtimes_u2534(colontmpD_);
		eqdestroy___pureZtimes_u2534(bytes);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
