# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_expiration_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akeyless_grpc.models import special_types_pb2 as models_dot_special__types__pb2

from akeyless_grpc.models.special_types_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)models/certificate_expiration_event.proto\x12\rakeyless_grpc\x1a\x1amodels/special_types.proto\"G\n\x1a\x43\x65rtificateExpirationEvent\x12)\n\x0eseconds_before\x18\xc1\x95\xd4_ \x01(\x03R\x0eseconds_beforeBQ\n\x11\x63om.akeyless.grpcP\x01Z\x0f.;akeyless_grpc\xaa\x02\rAkeyless.Grpc\xca\x02\rAkeyless\\gRPC\xe2\x02\x08MetadataP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.certificate_expiration_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.akeyless.grpcP\001Z\017.;akeyless_grpc\252\002\rAkeyless.Grpc\312\002\rAkeyless\\gRPC\342\002\010Metadata'
  _globals['_CERTIFICATEEXPIRATIONEVENT']._serialized_start=88
  _globals['_CERTIFICATEEXPIRATIONEVENT']._serialized_end=159
# @@protoc_insertion_point(module_scope)
