# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_issue_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akeyless_grpc.models import special_types_pb2 as models_dot_special__types__pb2
from akeyless_grpc.models import pki_certificate_issue_details_pb2 as models_dot_pki__certificate__issue__details__pb2
try:
  models_dot_special__types__pb2 = models_dot_pki__certificate__issue__details__pb2.models_dot_special__types__pb2
except AttributeError:
  models_dot_special__types__pb2 = models_dot_pki__certificate__issue__details__pb2.models.special_types_pb2
try:
  models_dot_certificate__expiration__event__pb2 = models_dot_pki__certificate__issue__details__pb2.models_dot_certificate__expiration__event__pb2
except AttributeError:
  models_dot_certificate__expiration__event__pb2 = models_dot_pki__certificate__issue__details__pb2.models.certificate_expiration_event_pb2
try:
  models_dot_special__types__pb2 = models_dot_pki__certificate__issue__details__pb2.models_dot_special__types__pb2
except AttributeError:
  models_dot_special__types__pb2 = models_dot_pki__certificate__issue__details__pb2.models.special_types_pb2
from akeyless_grpc.models import ssh_certificate_issue_details_pb2 as models_dot_ssh__certificate__issue__details__pb2
try:
  models_dot_special__types__pb2 = models_dot_ssh__certificate__issue__details__pb2.models_dot_special__types__pb2
except AttributeError:
  models_dot_special__types__pb2 = models_dot_ssh__certificate__issue__details__pb2.models.special_types_pb2

from akeyless_grpc.models.special_types_pb2 import *
from akeyless_grpc.models.pki_certificate_issue_details_pb2 import *
from akeyless_grpc.models.ssh_certificate_issue_details_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#models/certificate_issue_info.proto\x12\rakeyless_grpc\x1a\x1amodels/special_types.proto\x1a*models/pki_certificate_issue_details.proto\x1a*models/ssh_certificate_issue_details.proto\"\xb3\x02\n\x14\x43\x65rtificateIssueInfo\x12-\n\x10\x63\x65rt_issuer_type\x18\x9d\x99\xd6\x1d \x01(\tR\x10\x63\x65rt_issuer_type\x12\x1c\n\x07max_ttl\x18\x92\x89\xd5\x92\x01 \x01(\x03R\x07max_ttl\x12\x66\n\x17pki_cert_issuer_details\x18\xba\xb3\xfa\' \x01(\x0b\x32).akeyless_grpc.PkiCertificateIssueDetailsR\x17pki_cert_issuer_details\x12\x66\n\x17ssh_cert_issuer_details\x18\x80\xa3\xac\t \x01(\x0b\x32).akeyless_grpc.SshCertificateIssueDetailsR\x17ssh_cert_issuer_detailsBQ\n\x11\x63om.akeyless.grpcP\x01Z\x0f.;akeyless_grpc\xaa\x02\rAkeyless.Grpc\xca\x02\rAkeyless\\gRPC\xe2\x02\x08MetadataP\x00P\x01P\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.certificate_issue_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.akeyless.grpcP\001Z\017.;akeyless_grpc\252\002\rAkeyless.Grpc\312\002\rAkeyless\\gRPC\342\002\010Metadata'
  _globals['_CERTIFICATEISSUEINFO']._serialized_start=171
  _globals['_CERTIFICATEISSUEINFO']._serialized_end=478
# @@protoc_insertion_point(module_scope)
