# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/item_sra_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akeyless_grpc.models import special_types_pb2 as models_dot_special__types__pb2

from akeyless_grpc.models.special_types_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmodels/item_sra_status.proto\x12\rakeyless_grpc\x1a\x1amodels/special_types.proto\"\xed\x02\n\rItemSraStatus\x12K\n\x12\x63ount_by_host_info\x18\xaf\x80\xdf\xdd\x01 \x01(\x0b\x32\x17.akeyless_grpc.MapInt64R\x12\x63ount_by_host_info\x12O\n\ncount_info\x18\xa3\xc4\xdf\xed\x01 \x03(\x0b\x32+.akeyless_grpc.ItemSraStatus.CountInfoEntryR\ncount_info\x12&\n\x0chosts_in_use\x18\xa1\xcb\xb0\xfd\x01 \x03(\tR\x0chosts_in_use\x12\x1f\n\tis_in_use\x18\xdf\xd7\xbdW \x01(\x08R\tis_in_use\x12*\n\x0elast_used_item\x18\xed\xbf\xe7\xc9\x01 \x01(\tR\x0elast_used_item\x1aI\n\x0e\x43ountInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.akeyless_grpc.MapInt64:\x02\x38\x01\x42Q\n\x11\x63om.akeyless.grpcP\x01Z\x0f.;akeyless_grpc\xaa\x02\rAkeyless.Grpc\xca\x02\rAkeyless\\gRPC\xe2\x02\x08MetadataP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.item_sra_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.akeyless.grpcP\001Z\017.;akeyless_grpc\252\002\rAkeyless.Grpc\312\002\rAkeyless\\gRPC\342\002\010Metadata'
  _globals['_ITEMSRASTATUS_COUNTINFOENTRY']._options = None
  _globals['_ITEMSRASTATUS_COUNTINFOENTRY']._serialized_options = b'8\001'
  _globals['_ITEMSRASTATUS']._serialized_start=76
  _globals['_ITEMSRASTATUS']._serialized_end=441
  _globals['_ITEMSRASTATUS_COUNTINFOENTRY']._serialized_start=368
  _globals['_ITEMSRASTATUS_COUNTINFOENTRY']._serialized_end=441
# @@protoc_insertion_point(module_scope)
