# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/rotated_secret_details_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akeyless_grpc.models import special_types_pb2 as models_dot_special__types__pb2
from akeyless_grpc.models import windows_service_pb2 as models_dot_windows__service__pb2
try:
  models_dot_special__types__pb2 = models_dot_windows__service__pb2.models_dot_special__types__pb2
except AttributeError:
  models_dot_special__types__pb2 = models_dot_windows__service__pb2.models.special_types_pb2
try:
  models_dot_windows__service__attributes__pb2 = models_dot_windows__service__pb2.models_dot_windows__service__attributes__pb2
except AttributeError:
  models_dot_windows__service__attributes__pb2 = models_dot_windows__service__pb2.models.windows_service_attributes_pb2
try:
  models_dot_special__types__pb2 = models_dot_windows__service__pb2.models_dot_special__types__pb2
except AttributeError:
  models_dot_special__types__pb2 = models_dot_windows__service__pb2.models.special_types_pb2

from akeyless_grpc.models.special_types_pb2 import *
from akeyless_grpc.models.windows_service_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(models/rotated_secret_details_info.proto\x12\rakeyless_grpc\x1a\x1amodels/special_types.proto\x1a\x1cmodels/windows_service.proto\"\xef\x05\n\x18RotatedSecretDetailsInfo\x12L\n\x1f\x64\x65lete_previous_version_in_days\x18\xec\xa4\x98\xb8\x01 \x01(\x05R\x1f\x64\x65lete_previous_version_in_days\x12)\n\x0egrace_rotation\x18\xdb\x9f\xc9\x35 \x01(\x08R\x0egrace_rotation\x12\'\n\rgw_cluster_id\x18\xd2\x8f\x8f\x34 \x01(\x03R\rgw_cluster_id\x12\x33\n\x13last_rotation_error\x18\xb1\xea\x80\x04 \x01(\tR\x13last_rotation_error\x12&\n\x0cmax_versions\x18\xeb\xc9\xd0\xe9\x01 \x01(\x03R\x0cmax_versions\x12\x41\n\x1anumber_of_versions_to_save\x18\xf3\xba\xbek \x01(\x05R\x1anumber_of_versions_to_save\x12\'\n\rrotation_hour\x18\x85\xbc\x9ay \x01(\x05R\rrotation_hour\x12\x37\n\x15rotation_interval_min\x18\x87\xf2\xb4o \x01(\x08R\x15rotation_interval_min\x12\x31\n\x12rotation_statement\x18\xf1\xdb\xe9\x62 \x01(\tR\x12rotation_statement\x12\x31\n\x12rotator_creds_type\x18\xa7\x8c\xde# \x01(\tR\x12rotator_creds_type\x12)\n\x0erotator_status\x18\xbf\x9e\xba~ \x01(\tR\x0erotator_status\x12&\n\x0crotator_type\x18\xf6\x86\xbf\xd5\x01 \x01(\tR\x0crotator_type\x12\'\n\rsame_password\x18\xd5\xfc\xd0\x1b \x01(\x08R\rsame_password\x12M\n\x10services_details\x18\x9f\xa9\xc6\x8a\x01 \x03(\x0b\x32\x1d.akeyless_grpc.WindowsServiceR\x10services_detailsBQ\n\x11\x63om.akeyless.grpcP\x01Z\x0f.;akeyless_grpc\xaa\x02\rAkeyless.Grpc\xca\x02\rAkeyless\\gRPC\xe2\x02\x08MetadataP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.rotated_secret_details_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.akeyless.grpcP\001Z\017.;akeyless_grpc\252\002\rAkeyless.Grpc\312\002\rAkeyless\\gRPC\342\002\010Metadata'
  _globals['_ROTATEDSECRETDETAILSINFO']._serialized_start=118
  _globals['_ROTATEDSECRETDETAILSINFO']._serialized_end=869
# @@protoc_insertion_point(module_scope)
