# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/system_access_credentials_reply_obj.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from akeyless_grpc.models import special_types_pb2 as models_dot_special__types__pb2

from akeyless_grpc.models.special_types_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0models/system_access_credentials_reply_obj.proto\x12\rakeyless_grpc\x1a\x1amodels/special_types.proto\"\xe3\x01\n\x1fSystemAccessCredentialsReplyObj\x12\"\n\nauth_creds\x18\xf5\xd8\xc0\xac\x01 \x01(\tR\nauth_creds\x12\x19\n\x06\x65xpiry\x18\xcf\x85\xdc\x66 \x01(\x03R\x06\x65xpiry\x12 \n\tkfm_creds\x18\xab\xd6\x86\xaf\x01 \x01(\tR\tkfm_creds\x12%\n\x0crequired_mfa\x18\xbb\xcd\xbb\x08 \x01(\tR\x0crequired_mfa\x12\x17\n\x05token\x18\xf9\xf3\xda\x34 \x01(\tR\x05token\x12\x1f\n\tuam_creds\x18\x89\x95\x93k \x01(\tR\tuam_credsBQ\n\x11\x63om.akeyless.grpcP\x01Z\x0f.;akeyless_grpc\xaa\x02\rAkeyless.Grpc\xca\x02\rAkeyless\\gRPC\xe2\x02\x08MetadataP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.system_access_credentials_reply_obj_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.akeyless.grpcP\001Z\017.;akeyless_grpc\252\002\rAkeyless.Grpc\312\002\rAkeyless\\gRPC\342\002\010Metadata'
  _globals['_SYSTEMACCESSCREDENTIALSREPLYOBJ']._serialized_start=96
  _globals['_SYSTEMACCESSCREDENTIALSREPLYOBJ']._serialized_end=323
# @@protoc_insertion_point(module_scope)
