DEFAULT_BASE_URL = 'https://api.us-west.chaparral.ai'
DEFAULT_PROJECTS_ENDPOINT = 'projects'
DEFAULT_SEARCH_RESULTS_ENDPOINT = 'search_results'
DEFAULT_SEARCH_ENDPOINT = 'search'
DEFAULT_SEARCH_RESULTS_DOWNLOAD_ENDPOINT = 'download'
DEFAULT_PROJECT_FILES_ENDPOINT = 'files'
DEFAULT_PROFILE_ENDPOINT = 'profile'
DEFAULT_DATABASES_ENDPOINT = 'databases'
DEFAULT_ORGANIZATION_ENDPOINT = 'organization'
DEFAULT_ORGANIZATION_USAGE_ENDPOINT = 'usage'
DEFAULT_ORGANIZATION_INVITE_ENDPOINT = 'invite'
DEFAULT_SEARCH_RESULTS_SCORE_QC_ENDPOINT = 'qc/scores'
DEFAULT_SEARCH_RESULTS_IDS_QC_ENDPOINT = 'qc/ids'
DEFAULT_SEARCH_RESULTS_PRECURSORS_QC_ENDPOINT = 'qc/precursors'

CHAPARRAL_SERVERS = [
     'https://api.us-west.chaparral.ai',
]
