
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-24T16:41:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "477edd503c3420814d46fb5487a4bee81c4bbde1",
 "version": "0.0.043501"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
