
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-18T12:49:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "46e2b0eb9a7c8249177df775047fa098af26f6a6",
 "version": "1.3.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
