# Generated by Django 5.0.6 on 2024-07-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
    ]
