# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CustomManifest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, file=None):  # noqa: E501
        """CustomManifest - a model defined in OpenAPI

        :param name: The name of this CustomManifest.  # noqa: E501
        :type name: str
        :param file: The file of this CustomManifest.  # noqa: E501
        :type file: str
        """
        self.openapi_types = {
            'name': str,
            'file': str
        }

        self.attribute_map = {
            'name': 'name',
            'file': 'file'
        }

        self._name = name
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'CustomManifest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CustomManifest of this CustomManifest.  # noqa: E501
        :rtype: CustomManifest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CustomManifest.

        name of the custom_manifest deploy resource, which works as the identifier of the deploy-res, deploy-res-overlay and patch operation.  # noqa: E501

        :return: The name of this CustomManifest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomManifest.

        name of the custom_manifest deploy resource, which works as the identifier of the deploy-res, deploy-res-overlay and patch operation.  # noqa: E501

        :param name: The name of this CustomManifest.
        :type name: str
        """

        self._name = name

    @property
    def file(self):
        """Gets the file of this CustomManifest.

        source file name of the custom_manifest deploy resource.  # noqa: E501

        :return: The file of this CustomManifest.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this CustomManifest.

        source file name of the custom_manifest deploy resource.  # noqa: E501

        :param file: The file of this CustomManifest.
        :type file: str
        """

        self._file = file
