# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from th2_grpc_common import common_pb2 as th2__grpc__common_dot_common__pb2


class CodecStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.decode = channel.unary_unary(
                '/Codec/decode',
                request_serializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
                response_deserializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
                )
        self.encode = channel.unary_unary(
                '/Codec/encode',
                request_serializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
                response_deserializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
                )


class CodecServicer(object):
    """Missing associated documentation comment in .proto file."""

    def decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def encode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'decode': grpc.unary_unary_rpc_method_handler(
                    servicer.decode,
                    request_deserializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
                    response_serializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
            ),
            'encode': grpc.unary_unary_rpc_method_handler(
                    servicer.encode,
                    request_deserializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
                    response_serializer=th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Codec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Codec(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Codec/decode',
            th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
            th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Codec/encode',
            th2__grpc__common_dot_common__pb2.MessageGroupBatch.SerializeToString,
            th2__grpc__common_dot_common__pb2.MessageGroupBatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
