# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetRolesMappingSaasResult',
    'AwaitableGetRolesMappingSaasResult',
    'get_roles_mapping_saas',
    'get_roles_mapping_saas_output',
]

@pulumi.output_type
class GetRolesMappingSaasResult:
    """
    A collection of values returned by getRolesMappingSaas.
    """
    def __init__(__self__, id=None, roles_mappings=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if roles_mappings and not isinstance(roles_mappings, list):
            raise TypeError("Expected argument 'roles_mappings' to be a list")
        pulumi.set(__self__, "roles_mappings", roles_mappings)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="rolesMappings")
    def roles_mappings(self) -> Sequence['outputs.GetRolesMappingSaasRolesMappingResult']:
        return pulumi.get(self, "roles_mappings")


class AwaitableGetRolesMappingSaasResult(GetRolesMappingSaasResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRolesMappingSaasResult(
            id=self.id,
            roles_mappings=self.roles_mappings)


def get_roles_mapping_saas(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRolesMappingSaasResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_aquasec as aquasec

    roles_mapping_saas = aquasec.get_roles_mapping_saas()
    pulumi.export("roleMapping", roles_mapping_saas.roles_mappings)
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('aquasec:index/getRolesMappingSaas:getRolesMappingSaas', __args__, opts=opts, typ=GetRolesMappingSaasResult).value

    return AwaitableGetRolesMappingSaasResult(
        id=pulumi.get(__ret__, 'id'),
        roles_mappings=pulumi.get(__ret__, 'roles_mappings'))


@_utilities.lift_output_func(get_roles_mapping_saas)
def get_roles_mapping_saas_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetRolesMappingSaasResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_aquasec as aquasec

    roles_mapping_saas = aquasec.get_roles_mapping_saas()
    pulumi.export("roleMapping", roles_mapping_saas.roles_mappings)
    ```
    """
    ...
