# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DeploymentResourceStatusStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, health=None, sync=None):  # noqa: E501
        """DeploymentResourceStatusStatus - a model defined in OpenAPI

        :param health: The health of this DeploymentResourceStatusStatus.  # noqa: E501
        :type health: str
        :param sync: The sync of this DeploymentResourceStatusStatus.  # noqa: E501
        :type sync: str
        """
        self.openapi_types = {
            'health': str,
            'sync': str
        }

        self.attribute_map = {
            'health': 'health',
            'sync': 'sync'
        }

        self._health = health
        self._sync = sync

    @classmethod
    def from_dict(cls, dikt) -> 'DeploymentResourceStatusStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeploymentResourceStatus_status of this DeploymentResourceStatusStatus.  # noqa: E501
        :rtype: DeploymentResourceStatusStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def health(self):
        """Gets the health of this DeploymentResourceStatusStatus.


        :return: The health of this DeploymentResourceStatusStatus.
        :rtype: str
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this DeploymentResourceStatusStatus.


        :param health: The health of this DeploymentResourceStatusStatus.
        :type health: str
        """

        self._health = health

    @property
    def sync(self):
        """Gets the sync of this DeploymentResourceStatusStatus.


        :return: The sync of this DeploymentResourceStatusStatus.
        :rtype: str
        """
        return self._sync

    @sync.setter
    def sync(self, sync):
        """Sets the sync of this DeploymentResourceStatusStatus.


        :param sync: The sync of this DeploymentResourceStatusStatus.
        :type sync: str
        """

        self._sync = sync
