# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_container = QtWidgets.QWidget(self.centralwidget)
        self.graph_container.setObjectName("graph_container")
        self.verticalLayout.addWidget(self.graph_container)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Import = QtWidgets.QMenu(self.menu_File)
        self.menu_Import.setObjectName("menu_Import")
        self.menuExport = QtWidgets.QMenu(self.menu_File)
        self.menuExport.setObjectName("menuExport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGapSeq = QtWidgets.QAction(MainWindow)
        self.actionGapSeq.setObjectName("actionGapSeq")
        self.actionebFRET = QtWidgets.QAction(MainWindow)
        self.actionebFRET.setObjectName("actionebFRET")
        self.actionXXX = QtWidgets.QAction(MainWindow)
        self.actionXXX.setObjectName("actionXXX")
        self.menu_Import.addAction(self.actionGapSeq)
        self.menu_Import.addAction(self.actionebFRET)
        self.menuExport.addAction(self.actionXXX)
        self.menu_File.addAction(self.menu_Import.menuAction())
        self.menu_File.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Import.setTitle(_translate("MainWindow", "&Import"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.actionGapSeq.setText(_translate("MainWindow", "GapSeq"))
        self.actionebFRET.setText(_translate("MainWindow", "ebFRET"))
        self.actionXXX.setText(_translate("MainWindow", "XXX"))
