
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-24T08:05:59+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "4c1e89135072e3cd19222c3974451d54a6664ba7",
 "version": "0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
