
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-22T13:36:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e88d557440d37dbe1dc17f3fe5aa756c8fbacb15",
 "version": "2.3.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
