# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution_plan.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x65xecution_plan.proto\x12\x07\x62\x61uplan"\x9e\x02\n\nJobRequest\x12\x10\n\x08job_data\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tach\x18\x02 \x01(\x08\x12\x1b\n\x13\x64irect_connect_logs\x18\x03 \x01(\x08\x12\x1d\n\x04\x61rgs\x18\x05 \x03(\x0b\x32\x0f.bauplan.JobArg\x12"\n\x06status\x18\x06 \x01(\x0e\x32\x12.bauplan.JobStatus\x12\x1b\n\x13scheduled_runner_id\x18\x08 \x01(\t\x12\x1d\n\x10physical_plan_v2\x18\t \x01(\x0cH\x00\x88\x01\x01\x12\x18\n\x10scheduling_error\x18\n \x01(\tB\x13\n\x11_physical_plan_v2J\x04\x08\x04\x10\x05J\x04\x08\x07\x10\x08R\x05stepsR\x10physical_plan_id"$\n\x06JobArg\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t*[\n\tJobStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\x0c\n\x08\x43\x41NCELED\x10\x05\x42?Z=github.com/BauplanLabs/playground/commander-service/protobufsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_plan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals[
        'DESCRIPTOR'
    ]._serialized_options = b'Z=github.com/BauplanLabs/playground/commander-service/protobufs'
    _globals['_JOBSTATUS']._serialized_start = 360
    _globals['_JOBSTATUS']._serialized_end = 451
    _globals['_JOBREQUEST']._serialized_start = 34
    _globals['_JOBREQUEST']._serialized_end = 320
    _globals['_JOBARG']._serialized_start = 322
    _globals['_JOBARG']._serialized_end = 358
# @@protoc_insertion_point(module_scope)
