RAMO_VIDA = 1
RAMO_GMM = 2
RAMO_ACCIDENTES_INDIVIDUALES = 3
RAMO_GRUPO_VIDA = 4
RAMO_GRUPO_GMM = 5
RAMO_GRUPO_ACCIDENTES = 6
RAMO_AUTOS = 7
RAMO_CASAS = 8
RAMO_EMPRESAS = 9
RAMO_VARIOS = 10

MONEDA_PESO = 1
MONEDA_USD = 2
MONEDA_UDI = 3

PERIDO_PAGO_MENSUAL = 1
PERIDO_PAGO_TRIMESTRAL = 2
PERIDO_PAGO_SEMESTRAL = 3
PERIDO_PAGO_ANUAL = 4
PERIDO_PAGO_CONTADO = 5
PERIDO_PAGO_BIMESTRAL = 6

MEDIO_COBRO_TDC = 1
MEDIO_COBRO_TDD = 2
MEDIO_COBRO_AGE = 3
MEDIO_COBRO_MD = 4
MEDIO_COBRO_NOM = 5
MEDIO_COBRO_SIN = 6

ASEGURADORA_SMNYL = 1
ASEGURADORA_QUALITAS = 2
ASEGURADORA_GNP =3
ASEGURADORA_AXA = 4
ASEGURADORA_MAPFRE = 5
ASEGURADORA_ANA = 6