# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 1.1.6
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.json_patch_request_add_value import JSONPatchRequestAddValue

class TestJSONPatchRequestAddValue(unittest.TestCase):
    """JSONPatchRequestAddValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JSONPatchRequestAddValue:
        """Test JSONPatchRequestAddValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JSONPatchRequestAddValue`
        """
        model = JSONPatchRequestAddValue()
        if include_optional:
            return JSONPatchRequestAddValue(
            )
        else:
            return JSONPatchRequestAddValue(
        )
        """

    def testJSONPatchRequestAddValue(self):
        """Test JSONPatchRequestAddValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
