# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 1.1.6
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from antimatter_api.models.domain_add_read_context_rule200_response import DomainAddReadContextRule200Response

class TestDomainAddReadContextRule200Response(unittest.TestCase):
    """DomainAddReadContextRule200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainAddReadContextRule200Response:
        """Test DomainAddReadContextRule200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainAddReadContextRule200Response`
        """
        model = DomainAddReadContextRule200Response()
        if include_optional:
            return DomainAddReadContextRule200Response(
                id = 'rl-w8q6zgckec0l3o4g'
            )
        else:
            return DomainAddReadContextRule200Response(
        )
        """

    def testDomainAddReadContextRule200Response(self):
        """Test DomainAddReadContextRule200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
