from PySide2 import QtCore, QtWidgets
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 600)
        self.hBoxLayoutAll = QtWidgets.QHBoxLayout(Form)

        self.scrollArea = QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        self.scrollAreaContent = QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 646, 570))

        self.contentVBoxLayout = QVBoxLayout(self.scrollAreaContent)
        self.contentVBoxLayout.setContentsMargins(13, 13, 13, 13)
        self.contentVBoxLayout.setSpacing(6)

        self.hBoxLayout1 = QHBoxLayout()
        self.arqcLabel = QLabel("原始ARQC", parent=self.scrollAreaContent)
        self.arqc = QLineEdit("1233432423", parent=self.scrollAreaContent)
        self.ownerNameLabel = QLabel("持卡人姓名", parent=self.scrollAreaContent)
        self.owner_name = QLineEdit("李晓明", parent=self.scrollAreaContent)
        self.hBoxLayout1.addWidget(self.arqcLabel)
        self.hBoxLayout1.addWidget(self.arqc)
        self.hBoxLayout1.addWidget(self.ownerNameLabel)
        self.hBoxLayout1.addWidget(self.owner_name)

        self.hBoxLayout2 = QHBoxLayout()
        self.certTypeLabel = QLabel("证件类型", parent=self.scrollAreaContent)
        self.cert_type = QLineEdit("0-身份证", parent=self.scrollAreaContent)
        self.certNoLabel = QLabel("证件号", parent=self.scrollAreaContent)
        self.cert_no = QLineEdit("633276200128232826", parent=self.scrollAreaContent)
        self.hBoxLayout2.addWidget(self.certTypeLabel)
        self.hBoxLayout2.addWidget(self.cert_type)
        self.hBoxLayout2.addWidget(self.certNoLabel)
        self.hBoxLayout2.addWidget(self.cert_no)

        self.hBoxLayout3 = QHBoxLayout()
        self.serialLabel = QLabel("卡序号", parent=self.scrollAreaContent)
        self.card_serial_no = QLineEdit("01", parent=self.scrollAreaContent)
        self.cardNoLabel = QLabel("卡号", parent=self.scrollAreaContent)
        self.card_no = QLineEdit("92873912471938913", parent=self.scrollAreaContent)
        self.hBoxLayout3.addWidget(self.serialLabel)
        self.hBoxLayout3.addWidget(self.card_serial_no)
        self.hBoxLayout3.addWidget(self.cardNoLabel)
        self.hBoxLayout3.addWidget(self.card_no)

        self.hBoxLayout4 = QHBoxLayout()
        self.ccyLabel = QLabel("币种", parent=self.scrollAreaContent)
        self.ccy = QLineEdit("0-人民币", parent=self.scrollAreaContent)
        self.balanceLabel = QLabel("电子现金余额", parent=self.scrollAreaContent)
        self.balance = QLineEdit("1000", parent=self.scrollAreaContent)
        self.hBoxLayout4.addWidget(self.ccyLabel)
        self.hBoxLayout4.addWidget(self.ccy)
        self.hBoxLayout4.addWidget(self.balanceLabel)
        self.hBoxLayout4.addWidget(self.balance)

        self.hBoxLayout5 = QHBoxLayout()
        self.issueLabel = QLabel("发卡行应用数据", parent=self.scrollAreaContent)
        self.issue_branch_data = QLineEdit("1312", parent=self.scrollAreaContent)
        self.aidLabel = QLabel("应用标识", parent=self.scrollAreaContent)
        self.aid = QLineEdit("A000000333010101", parent=self.scrollAreaContent)
        self.hBoxLayout5.addWidget(self.issueLabel)
        self.hBoxLayout5.addWidget(self.issue_branch_data)
        self.hBoxLayout5.addWidget(self.aidLabel)
        self.hBoxLayout5.addWidget(self.aid)

        self.hBoxLayout6 = QHBoxLayout()
        self.balanceLabel = QLabel("余额上限", parent=self.scrollAreaContent)
        self.balance_limit = QLineEdit("1000", parent=self.scrollAreaContent)
        self.singleLabel = QLabel("单笔金额上限", parent=self.scrollAreaContent)
        self.single_limit = QLineEdit("1000", parent=self.scrollAreaContent)
        self.hBoxLayout6.addWidget(self.balanceLabel)
        self.hBoxLayout6.addWidget(self.balance_limit)
        self.hBoxLayout6.addWidget(self.singleLabel)
        self.hBoxLayout6.addWidget(self.single_limit)

        self.hBoxLayout7 = QHBoxLayout()
        self.counterLabel = QLabel("应用交易计数器", parent=self.scrollAreaContent)
        self.tran_counter = QLineEdit("1", parent=self.scrollAreaContent)
        self.verifyLabel = QLabel("终端验证结果", parent=self.scrollAreaContent)
        self.verify_result = QLineEdit("1", parent=self.scrollAreaContent)
        self.hBoxLayout7.addWidget(self.counterLabel)
        self.hBoxLayout7.addWidget(self.tran_counter)
        self.hBoxLayout7.addWidget(self.verifyLabel)
        self.hBoxLayout7.addWidget(self.verify_result)

        self.hBoxLayout8 = QHBoxLayout()
        self.effectiveLabel = QLabel("应用生效日期", parent=self.scrollAreaContent)
        self.effective_date = QLineEdit("2001/01/01", parent=self.scrollAreaContent)
        self.overdueLabel = QLabel("应用失效日期", parent=self.scrollAreaContent)
        self.overdue_date = QLineEdit("2031/01/01", parent=self.scrollAreaContent)
        self.hBoxLayout8.addWidget(self.effectiveLabel)
        self.hBoxLayout8.addWidget(self.effective_date)
        self.hBoxLayout8.addWidget(self.overdueLabel)
        self.hBoxLayout8.addWidget(self.overdue_date)

        self.hBoxLayout9 = QHBoxLayout()
        self.pbocLabel = QLabel("支持PBOC版本", parent=self.scrollAreaContent)
        self.pboc_ver = QLineEdit("2.0", parent=self.scrollAreaContent)
        self.contactLabel = QLabel("IC卡接触方式", parent=self.scrollAreaContent)
        self.contact_mode = QLineEdit("接触式", parent=self.scrollAreaContent)
        self.hBoxLayout9.addWidget(self.pbocLabel)
        self.hBoxLayout9.addWidget(self.pboc_ver)
        self.hBoxLayout9.addWidget(self.contactLabel)
        self.hBoxLayout9.addWidget(self.contact_mode)

        self.hBoxLayout10 = QHBoxLayout()
        self.sourceLabel = QLabel("ARQC源数据", parent=self.scrollAreaContent)
        self.arqc_source = QLineEdit("1234567890", parent=self.scrollAreaContent)
        self.hBoxLayout10.addWidget(self.sourceLabel)
        self.hBoxLayout10.addWidget(self.arqc_source)

        self.hBoxLayout11 = QHBoxLayout()
        self.onlylabel = QLabel("加密ARQC", parent=self.scrollAreaContent)
        self.arqc_only = QLineEdit("abcdefghijklmn12345", parent=self.scrollAreaContent)
        self.hBoxLayout11.addWidget(self.onlylabel)
        self.hBoxLayout11.addWidget(self.arqc_only)

        self.hBoxLayout12 = QHBoxLayout()
        self.track2DataLabel = QLabel("二磁道等效数据", parent=self.scrollAreaContent)
        self.track2Data = QLineEdit("6217998340006985046=28092200200600000", parent=self.scrollAreaContent)
        self.hBoxLayout12.addWidget(self.track2DataLabel)
        self.hBoxLayout12.addWidget(self.track2Data)

        self.hBoxLayout13 = QVBoxLayout()
        self.groupBox = QGroupBox("交易详情")
        self.groupBoxLayout = QVBoxLayout()
        self.groupBox.setLayout(self.groupBoxLayout)
        self.tran_detail = QTableWidget()
        self.groupBoxLayout.addWidget(self.tran_detail)
        self.tran_detail.setColumnCount(9)
        self.tran_detail.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.tran_detail.setHorizontalHeaderLabels(
            ["交易货币代码", "授权金额", "其他金额", "交易日期", "交易时间", "交易类型", "商户名称", "终端国家代码",
             "应用交易计数器"])
        self.tran_detail.setRowCount(2)
        data = [["20230001", "100000", "200000", "2023/09/21", "10:23:02", "正常交易", "张三", "A-03-0001", "1"],
                ["20230002", "192333", "300550", "2024/01/21", "17:45:21", "正常交易", "李四", "A-03-0001", "1"]]
        for rowIndex, rowData in enumerate(data):
            for columnIndex, columnData in enumerate(rowData):
                self.tran_detail.setItem(rowIndex, columnIndex, QTableWidgetItem(columnData))
        self.hBoxLayout13.addWidget(self.groupBox)
        self.hBoxLayout14 = QHBoxLayout()
        self.spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.confirm = QPushButton("确定", parent=self.scrollAreaContent)
        self.confirm.setStyleSheet("background-color: rgb(225, 241, 255);")
        self.hBoxLayout14.addItem(self.spacerItem)
        self.hBoxLayout14.addWidget(self.confirm)

        self.contentVBoxLayout.addLayout(self.hBoxLayout1)
        self.contentVBoxLayout.addLayout(self.hBoxLayout2)
        self.contentVBoxLayout.addLayout(self.hBoxLayout3)
        self.contentVBoxLayout.addLayout(self.hBoxLayout4)
        self.contentVBoxLayout.addLayout(self.hBoxLayout5)
        self.contentVBoxLayout.addLayout(self.hBoxLayout6)
        self.contentVBoxLayout.addLayout(self.hBoxLayout7)
        self.contentVBoxLayout.addLayout(self.hBoxLayout8)
        self.contentVBoxLayout.addLayout(self.hBoxLayout9)
        self.contentVBoxLayout.addLayout(self.hBoxLayout10)
        self.contentVBoxLayout.addLayout(self.hBoxLayout11)
        self.contentVBoxLayout.addLayout(self.hBoxLayout12)
        self.contentVBoxLayout.addLayout(self.hBoxLayout13)
        self.contentVBoxLayout.addLayout(self.hBoxLayout14)
        self.scrollArea.setWidget(self.scrollAreaContent)
        self.hBoxLayoutAll.addWidget(self.scrollArea)
