from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtWidgets import QSizePolicy, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit, QSpacerItem, QComboBox, \
    QPushButton, QLayout


class Ui_Form(object):
    def setupUi(self, Form):
        Form.resize(650, 500)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)

        self.vBoxLayout = QVBoxLayout(Form)
        self.vBoxLayout.setContentsMargins(40, 20, 40, 40)

        self.hBoxLayout1 = QHBoxLayout()
        self.cnNameLabel = QLabel("姓     名", parent=Form)
        self.cnName = QLineEdit("张小龙", parent=Form)
        self.spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.sexLabel = QLabel("性    别", parent=Form)
        self.sex = QLineEdit("男", parent=Form)
        self.hBoxLayout1.addWidget(self.cnNameLabel)
        self.hBoxLayout1.addWidget(self.cnName)
        self.hBoxLayout1.addItem(self.spacerItem1)
        self.hBoxLayout1.addWidget(self.sexLabel)
        self.hBoxLayout1.addWidget(self.sex)

        self.hBoxLayout2 = QHBoxLayout()
        self.nationLabel = QLabel("名     族", parent=Form)
        self.nation = QLineEdit("汉", parent=Form)
        self.spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.birthdayLabel = QLabel("出生日期", parent=Form)
        self.birthday = QLineEdit("2000/01/01", parent=Form)
        self.hBoxLayout2.addWidget(self.nationLabel)
        self.hBoxLayout2.addWidget(self.nation)
        self.hBoxLayout2.addItem(self.spacerItem2)
        self.hBoxLayout2.addWidget(self.birthdayLabel)
        self.hBoxLayout2.addWidget(self.birthday)

        self.hBoxLayout3 = QHBoxLayout()
        self.addressLabel = QLabel("居住地址", parent=Form)
        self.address = QLineEdit("陕西省西安市雁塔区鱼化寨街道高档小区8号楼1101", parent=Form)
        self.hBoxLayout3.addWidget(self.addressLabel)
        self.hBoxLayout3.addWidget(self.address)

        self.hBoxLayout4 = QHBoxLayout()
        self.idLabel = QLabel("身份证号", parent=Form)
        self.id = QLineEdit("622654200808082379", parent=Form)
        self.hBoxLayout4.addWidget(self.idLabel)
        self.hBoxLayout4.addWidget(self.id)

        self.hBoxLayout5 = QHBoxLayout()
        self.depLabel = QLabel("发证机关", parent=Form)
        self.dep = QLineEdit("陕西省西安市公安局", parent=Form)
        self.hBoxLayout5.addWidget(self.depLabel)
        self.hBoxLayout5.addWidget(self.dep)

        self.hBoxLayout6 = QHBoxLayout()
        self.beginDateLabel = QLabel("生效日期", parent=Form)
        self.beginDate = QLineEdit("2000/01/01", parent=Form)
        self.spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.endDateLabel = QLabel("截止日期", parent=Form)
        self.endDate = QLineEdit("2000/01/01", parent=Form)
        self.hBoxLayout6.addWidget(self.beginDateLabel)
        self.hBoxLayout6.addWidget(self.beginDate)
        self.hBoxLayout6.addItem(self.spacerItem3)
        self.hBoxLayout6.addWidget(self.endDateLabel)
        self.hBoxLayout6.addWidget(self.endDate)

        self.hBoxLayout7 = QHBoxLayout()
        self.imagePathLabel = QLabel("身份证头像存储绝对路径", parent=Form)
        self.imagePath = QLineEdit("E://Temp/file", parent=Form)
        self.hBoxLayout7.addWidget(self.imagePathLabel)
        self.hBoxLayout7.addWidget(self.imagePath)

        self.hBoxLayout8 = QHBoxLayout()
        self.imageInfoLabel = QLabel("身份证头像BASE64 数据", parent=Form)
        self.imageInfo = QLineEdit("nc808ryocq8yrnx3hnx839xnxz983x9cn348cy9", parent=Form)
        self.hBoxLayout8.addWidget(self.imageInfoLabel)
        self.hBoxLayout8.addWidget(self.imageInfo)

        self.hBoxLayout9 = QHBoxLayout()
        self.spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.confirm = QPushButton("确定", parent=Form)
        self.confirm.setMaximumSize(QtCore.QSize(85, 35))
        self.confirm.setStyleSheet("background-color: rgb(225, 241, 255);")
        self.hBoxLayout9.addItem(self.spacerItem4)
        self.hBoxLayout9.addWidget(self.confirm)

        self.vBoxLayout.addLayout(self.hBoxLayout1)
        self.vBoxLayout.addLayout(self.hBoxLayout1)
        self.vBoxLayout.addLayout(self.hBoxLayout2)
        self.vBoxLayout.addLayout(self.hBoxLayout3)
        self.vBoxLayout.addLayout(self.hBoxLayout4)
        self.vBoxLayout.addLayout(self.hBoxLayout5)
        self.vBoxLayout.addLayout(self.hBoxLayout6)
        self.vBoxLayout.addLayout(self.hBoxLayout7)
        self.vBoxLayout.addLayout(self.hBoxLayout8)
        self.vBoxLayout.addLayout(self.hBoxLayout9)
