
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-25T15:48:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3720a68e0890377e79a5734916e31de7001aeb4e",
 "version": "2024.7.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
