# Generated by Django 5.0.6 on 2024-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("command", models.CharField(max_length=255)),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.IntegerField()),
            ],
            options={
                "db_table": "django_command_message",
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
