/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tyTuple__HKalArfYTzTC9bE4LdiUViQ tyTuple__HKalArfYTzTC9bE4LdiUViQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyTuple__HKalArfYTzTC9bE4LdiUViQ {
NU32 Field0;
NI Field1;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4581)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2390)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorU)(NU64 i_p0, NU64 a_p1, NU64 b_p2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4363;
extern NIM_THREADVAR TFrame* framePtr__system_u3980;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4363);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3980 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3980).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3980;
	framePtr__system_u3980 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4581();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3980 = (*framePtr__system_u3980).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__HKalArfYTzTC9bE4LdiUViQ, varint__librariesZsupersnappyZsupersnappyZcommon_u79)(NimStringV2 buf_p0) {
	tyTuple__HKalArfYTzTC9bE4LdiUViQ result;
	NU8 b;
	NU32 colontmp__9;
	NI colontmp__10;
	nimfr_("varint", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\libraries\\supersnappy\\supersnappy\\common.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__HKalArfYTzTC9bE4LdiUViQ));
	nimln_(68);
	{
		if (!(buf_p0.len == ((NI)0))) goto LA3_;
		nimln_(69);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(71);
	if (((NI)0) < 0 || ((NI)0) >= buf_p0.len){ raiseIndexError2(((NI)0),buf_p0.len-1); goto BeforeRet_;
	}
	b = ((NU8) (((NU8)(buf_p0.p->data[((NI)0)]))));
	nimln_(72);
	result.Field0 = ((NU32) ((NU8)(b & ((NU8)127))));
	nimln_(73);
	result.Field1 = ((NI)1);
	nimln_(74);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA7_;
		nimln_(75);
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(76);
	{
		NU32 colontmp_;
		NI colontmp__2;
		if (!(buf_p0.len == ((NI)1))) goto LA11_;
		nimln_(77);
		colontmp_ = ((NU32)0);
		colontmp__2 = ((NI)0);
		nimln_(67);
		nimln_(77);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA11_: ;
	nimln_(78);
	if (((NI)1) < 0 || ((NI)1) >= buf_p0.len){ raiseIndexError2(((NI)1),buf_p0.len-1); goto BeforeRet_;
	}
	b = ((NU8) (((NU8)(buf_p0.p->data[((NI)1)]))));
	nimln_(79);
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)7))));
	nimln_(80);
	result.Field1 = ((NI)2);
	nimln_(81);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA15_;
		nimln_(82);
		goto BeforeRet_;
	}
LA15_: ;
	nimln_(83);
	{
		NU32 colontmp__3;
		NI colontmp__4;
		if (!(buf_p0.len == ((NI)2))) goto LA19_;
		nimln_(84);
		colontmp__3 = ((NU32)0);
		colontmp__4 = ((NI)0);
		nimln_(67);
		nimln_(84);
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA19_: ;
	nimln_(85);
	if (((NI)2) < 0 || ((NI)2) >= buf_p0.len){ raiseIndexError2(((NI)2),buf_p0.len-1); goto BeforeRet_;
	}
	b = ((NU8) (((NU8)(buf_p0.p->data[((NI)2)]))));
	nimln_(86);
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)14))));
	nimln_(87);
	result.Field1 = ((NI)3);
	nimln_(88);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA23_;
		nimln_(89);
		goto BeforeRet_;
	}
LA23_: ;
	nimln_(90);
	{
		NU32 colontmp__5;
		NI colontmp__6;
		if (!(buf_p0.len == ((NI)3))) goto LA27_;
		nimln_(91);
		colontmp__5 = ((NU32)0);
		colontmp__6 = ((NI)0);
		nimln_(67);
		nimln_(91);
		result.Field0 = colontmp__5;
		result.Field1 = colontmp__6;
		goto BeforeRet_;
	}
LA27_: ;
	nimln_(92);
	if (((NI)3) < 0 || ((NI)3) >= buf_p0.len){ raiseIndexError2(((NI)3),buf_p0.len-1); goto BeforeRet_;
	}
	b = ((NU8) (((NU8)(buf_p0.p->data[((NI)3)]))));
	nimln_(93);
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)21))));
	nimln_(94);
	result.Field1 = ((NI)4);
	nimln_(95);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA31_;
		nimln_(96);
		goto BeforeRet_;
	}
LA31_: ;
	nimln_(97);
	{
		NU32 colontmp__7;
		NI colontmp__8;
		if (!(buf_p0.len == ((NI)4))) goto LA35_;
		nimln_(98);
		colontmp__7 = ((NU32)0);
		colontmp__8 = ((NI)0);
		nimln_(67);
		nimln_(98);
		result.Field0 = colontmp__7;
		result.Field1 = colontmp__8;
		goto BeforeRet_;
	}
LA35_: ;
	nimln_(99);
	if (((NI)4) < 0 || ((NI)4) >= buf_p0.len){ raiseIndexError2(((NI)4),buf_p0.len-1); goto BeforeRet_;
	}
	b = ((NU8) (((NU8)(buf_p0.p->data[((NI)4)]))));
	nimln_(100);
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)28))));
	nimln_(101);
	result.Field1 = ((NI)5);
	nimln_(102);
	{
		if (!((NU8)(b) < (NU8)(((NU8)16)))) goto LA39_;
		nimln_(103);
		goto BeforeRet_;
	}
LA39_: ;
	nimln_(104);
	colontmp__9 = ((NU32)0);
	colontmp__10 = ((NI)0);
	nimln_(67);
	nimln_(104);
	result.Field0 = colontmp__9;
	result.Field1 = colontmp__10;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2390(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, varint__librariesZsupersnappyZsupersnappyZcommon_u20)(NU32 value_p0) {
	NimStringV2 result;
	nimfr_("varint", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\libraries\\supersnappy\\supersnappy\\common.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(41);
	{
		if (!((NU32)(value_p0) < (NU32)(((NU32)128)))) goto LA3_;
		nimln_(42);
		setLengthStrV2((&result), ((NI)1));
		nimln_(43);
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)(value_p0) < 0 || (NI64)(value_p0) > 255){ raiseRangeErrorU(value_p0, 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (value_p0));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(44);
		if (!((NU32)(value_p0) < (NU32)(((NU32)16384)))) goto LA6_;
		nimln_(45);
		setLengthStrV2((&result), ((NI)2));
		nimln_(46);
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		nimln_(47);
		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) & ((NU32)255))));
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(48);
		if (!((NU32)(value_p0) < (NU32)(((NU32)2097152)))) goto LA9_;
		nimln_(49);
		setLengthStrV2((&result), ((NI)3));
		nimln_(50);
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		nimln_(51);
		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		nimln_(52);
		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) & ((NU32)255))));
	}
	goto LA1_;
LA9_: ;
	{
		nimln_(53);
		if (!((NU32)(value_p0) < (NU32)(((NU32)268435456)))) goto LA12_;
		nimln_(54);
		setLengthStrV2((&result), ((NI)4));
		nimln_(55);
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		nimln_(56);
		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		nimln_(57);
		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))));
		nimln_(58);
		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) & ((NU32)255))));
	}
	goto LA1_;
LA12_: ;
	{
		nimln_(60);
		setLengthStrV2((&result), ((NI)5));
		nimln_(61);
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		nimln_(62);
		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		nimln_(63);
		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))));
		nimln_(64);
		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) | ((NU32)128)) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) | ((NU32)128)) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) | ((NU32)128)) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) | ((NU32)128)) & ((NU32)255))));
		nimln_(65);
		if (((NI)4) < 0 || ((NI)4) >= result.len){ raiseIndexError2(((NI)4),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)28))) & ((NU32)255))) < 0 || (NI64)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)28))) & ((NU32)255))) > 255){ raiseRangeErrorU((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)28))) & ((NU32)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[((NI)4)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)28))) & ((NU32)255))));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
