/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n) \
    FR_.line = n;

  #define nimlf_(n, file) \
    FR_.line = n; FR_.filename = file;

typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g;
typedef struct tyObject_point__MN7UdrA9cGABfr4tCur5RbQ tyObject_point__MN7UdrA9cGABfr4tCur5RbQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ tySequence__7s5HyddQ0f9bxMNILHrXwJQ;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content;
typedef struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ;
typedef struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content;
typedef struct tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA;
typedef struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA tySequence__UrPRVZYp6MbnOWXK4N9bUkA;
typedef struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content;
typedef struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ tySequence__owY9b1no7B0PqDQ8zV5DrxQ;
typedef struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content;
typedef struct tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A;
typedef struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g tyTuple__kuMQ1fbjJlHtwKTmBGAe6g;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
typedef NU16 tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ;
struct tyObject_point__MN7UdrA9cGABfr4tCur5RbQ {
	NI16 x;
	NI16 y;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ {
  NI len; tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content* p;
};
struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA {
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ data;
	NI counter;
};
struct tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g {
	tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ kind;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ position;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ custom_displacement;
	NU8 rotation;
	NI8 real_offset;
	NI permanent_id;
	NimStringV2 custom_string;
	NI custom_id;
	NU64 setting1;
	NU64 setting2;
	tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA selected_programs;
	NI16 ui_order;
};
struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ {
  NI len; tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content* p;
};
typedef NU8 tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw;
struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA {
  NI len; tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content* p;
};
struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ {
  NI len; tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content* p;
};
struct tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA {
	NU8 version;
	tySequence__UrPRVZYp6MbnOWXK4N9bUkA components;
	tySequence__owY9b1no7B0PqDQ8zV5DrxQ wires;
	NI save_id;
	NU32 hub_id;
	NimStringV2 hub_description;
	NI gate;
	NI delay;
	NIM_BOOL menu_visible;
	NU32 clock_speed;
	tySequence__qwqHTkRvwhrRyENtudHQ7g dependencies;
	NimStringV2 description;
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ camera_position;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ player_data;
	tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw synced;
	NIM_BOOL campaign_bound;
};
typedef NU8 tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw;
struct tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A {
	tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ path;
	tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw kind;
	NU8 color;
	NimStringV2 comment;
};
typedef tyObject_point__MN7UdrA9cGABfr4tCur5RbQ tyArray__UfdIMDE1tgdULaKrSRVsiw[8];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g {
NI Field0;
NI Field1;
NimStringV2 Field2;
};
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ_Content { NI cap; tyTuple__kuMQ1fbjJlHtwKTmBGAe6g data[SEQ_DECL_SIZE]; };
struct tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ_Content { NI cap; tyObject_point__MN7UdrA9cGABfr4tCur5RbQ data[SEQ_DECL_SIZE]; };
struct tySequence__UrPRVZYp6MbnOWXK4N9bUkA_Content { NI cap; tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g data[SEQ_DECL_SIZE]; };
struct tySequence__owY9b1no7B0PqDQ8zV5DrxQ_Content { NI cap; tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4581)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___common_u846)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___common_u1527)(tySequence__7s5HyddQ0f9bxMNILHrXwJQ dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___common_u1919)(tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NU16, get_u16__common_u445)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__common_u529)(tySequence__qwqHTkRvwhrRyENtudHQ7g* x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(NI, get_int__common_u377)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, get_u8__common_u465)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addlen_p1);
N_LIB_PRIVATE N_NIMCALL(NI16, get_i16__common_u461)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, get_u32__common_u421)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZtimes_u2492)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8 y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___versionsZv48_u475)(tySequence__UrPRVZYp6MbnOWXK4N9bUkA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___versionsZv48_u635)(tySequence__owY9b1no7B0PqDQ8zV5DrxQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2534)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, add_u16__common_u680)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU16 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_int__common_u575)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NI input_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u310)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, add_u8__common_u718)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU8 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_i16__common_u699)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NI16 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_u32__common_u645)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU32 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_point__common_u761)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ input_p1);
static N_INLINE(NI, find__common_u1762)(tyArray__UfdIMDE1tgdULaKrSRVsiw a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ item_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___common_u1835)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ x_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, minus___common_u361)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ b_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static const struct {
  NI cap; NIM_CHAR data[150+1];
} TM__IYKT5L9bjnVwc9cm3VCRe7wQ_33 = { 150 | NIM_STRLIT_FLAG, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__IYKT5L9bjnVwc9cm3VCRe7wQ_34 = {150, (NimStrPayload*)&TM__IYKT5L9bjnVwc9cm3VCRe7wQ_33};
static const struct {
  NI cap; NIM_CHAR data[153+1];
} TM__IYKT5L9bjnVwc9cm3VCRe7wQ_36 = { 153 | NIM_STRLIT_FLAG, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim(264, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__IYKT5L9bjnVwc9cm3VCRe7wQ_37 = {153, (NimStrPayload*)&TM__IYKT5L9bjnVwc9cm3VCRe7wQ_36};
static const NimStringV2 TM__IYKT5L9bjnVwc9cm3VCRe7wQ_39 = {150, (NimStrPayload*)&TM__IYKT5L9bjnVwc9cm3VCRe7wQ_33};
N_LIB_PRIVATE NIM_CONST tyArray__UfdIMDE1tgdULaKrSRVsiw DIRECTIONS__common_u278 = {{((NI16)1), ((NI16)0)}
,
{((NI16)1), ((NI16)1)}
,
{((NI16)0), ((NI16)1)}
,
{((NI16)-1), ((NI16)1)}
,
{((NI16)-1), ((NI16)0)}
,
{((NI16)-1), ((NI16)-1)}
,
{((NI16)0), ((NI16)-1)}
,
{((NI16)1), ((NI16)-1)}
}
;
extern NIM_THREADVAR TFrame* framePtr__system_u3980;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4363;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u3980 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u3980).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u3980;
	framePtr__system_u3980 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4581();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u3980 = (*framePtr__system_u3980).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, get_int__common_u377)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NI result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_4;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_6;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_8;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_10;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_12;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_14;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_16;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_17;
	nimfr_("get_int", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NI)0;
	nimln_(396);
	nimln_(402);
	nimln_(401);
	nimln_(400);
	nimln_(399);
	nimln_(398);
	nimln_(397);
	nimln_(396);
	if (nimAddInt((*i_p1), ((NI)0), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2),input_p0.len-1); goto BeforeRet_;
	}
	nimln_(397);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_2)]))) << (NU64)(((NI)0))), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_3)]))) << (NU64)(((NI)8))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_4)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(398);
	if (nimAddInt((*i_p1), ((NI)2), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_4), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_5)]))) << (NU64)(((NI)16))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(399);
	if (nimAddInt((*i_p1), ((NI)3), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_6), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_7)]))) << (NU64)(((NI)24))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_8)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(400);
	if (nimAddInt((*i_p1), ((NI)4), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_8), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_9)]))) << (NU64)(((NI)32))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_10)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(401);
	if (nimAddInt((*i_p1), ((NI)5), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_10), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_11)]))) << (NU64)(((NI)40))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_12)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(402);
	if (nimAddInt((*i_p1), ((NI)6), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_12), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_13)]))) << (NU64)(((NI)48))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_14)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(403);
	if (nimAddInt((*i_p1), ((NI)7), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15),input_p0.len-1); goto BeforeRet_;
	}
	if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_14), (NI)((NU64)(((NI) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_15)]))) << (NU64)(((NI)56))), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_16)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_16);
	nimln_(404);
	if (nimAddInt((*i_p1), ((NI)8), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_17)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_17);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, get_u32__common_u421)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NU32 result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_22;
	nimfr_("get_u32", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NU32)0;
	nimln_(410);
	nimln_(412);
	nimln_(411);
	nimln_(410);
	if (nimAddInt((*i_p1), ((NI)0), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18),input_p0.len-1); goto BeforeRet_;
	}
	nimln_(411);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19),input_p0.len-1); goto BeforeRet_;
	}
	nimln_(412);
	if (nimAddInt((*i_p1), ((NI)2), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20),input_p0.len-1); goto BeforeRet_;
	}
	nimln_(413);
	if (nimAddInt((*i_p1), ((NI)3), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21),input_p0.len-1); goto BeforeRet_;
	}
	result = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_18)]))) << (NU64)(((NI)0)))) + (NU32)((NU32)((NU64)(((NU32) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_19)]))) << (NU64)(((NI)8)))))) + (NU32)((NU32)((NU64)(((NU32) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_20)]))) << (NU64)(((NI)16)))))) + (NU32)((NU32)((NU64)(((NU32) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_21)]))) << (NU64)(((NI)24)))));
	nimln_(414);
	if (nimAddInt((*i_p1), ((NI)4), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_22)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_22);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, get_bool__common_u369)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NIM_BOOL result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_23;
	nimfr_("get_bool", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NIM_BOOL)0;
	nimln_(392);
	if ((*i_p1) < 0 || (*i_p1) >= input_p0.len){ raiseIndexError2((*i_p1),input_p0.len-1); goto BeforeRet_;
	}
	result = !((input_p0.p->data[(*i_p1)] == ((NU8)0)));
	nimln_(393);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_23)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_23);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, get_u8__common_u465)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NU8 result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_24;
	nimfr_("get_u8", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NU8)0;
	nimln_(425);
	if ((*i_p1) < 0 || (*i_p1) >= input_p0.len){ raiseIndexError2((*i_p1),input_p0.len-1); goto BeforeRet_;
	}
	result = input_p0.p->data[(*i_p1)];
	nimln_(426);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_24)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_24);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___common_u846)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NI));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___common_u855)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___common_u846((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(NU16, get_u16__common_u445)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NU16 result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_27;
	nimfr_("get_u16", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NU16)0;
	nimln_(417);
	if (nimAddInt((*i_p1), ((NI)0), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25),input_p0.len-1); goto BeforeRet_;
	}
	nimln_(418);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26) >= input_p0.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26),input_p0.len-1); goto BeforeRet_;
	}
	result = (NU16)((NU16)((NU16)((NU64)(((NU16) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_25)]))) << (NU64)(((NI)0)))) + (NU16)((NU16)((NU64)(((NU16) (input_p0.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_26)]))) << (NU64)(((NI)8)))));
	nimln_(419);
	if (nimAddInt((*i_p1), ((NI)2), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_27)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_27);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI8, get_i8__common_u473)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NI8 result;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_28;
	nimfr_("get_i8", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	result = (NI8)0;
	nimln_(429);
	if ((*i_p1) < 0 || (*i_p1) >= input_p0.len){ raiseIndexError2((*i_p1),input_p0.len-1); goto BeforeRet_;
	}
	result = ((NI8) (input_p0.p->data[(*i_p1)]));
	nimln_(430);
	if (nimAddInt((*i_p1), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_28)) { raiseOverflow(); goto BeforeRet_;
	};
	(*i_p1) = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_28);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_u4363);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___versionsZv48_u289)(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if ((*dest_p0).custom_string.p && !((*dest_p0).custom_string.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).custom_string.p);
}
	eqdestroy___common_u1527((*dest_p0).selected_programs.data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___versionsZv48_u286)(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* dest_p0) {
	(*dest_p0).kind = 0;
	(*dest_p0).position.x = 0;
	(*dest_p0).position.y = 0;
	(*dest_p0).custom_displacement.x = 0;
	(*dest_p0).custom_displacement.y = 0;
	(*dest_p0).rotation = 0;
	(*dest_p0).real_offset = 0;
	(*dest_p0).permanent_id = 0;
	(*dest_p0).custom_string.len = 0; (*dest_p0).custom_string.p = NIM_NIL;
	(*dest_p0).custom_id = 0;
	(*dest_p0).setting1 = 0;
	(*dest_p0).setting2 = 0;
	(*dest_p0).selected_programs.data.len = 0; (*dest_p0).selected_programs.data.p = NIM_NIL;
	(*dest_p0).selected_programs.counter = 0;
	(*dest_p0).ui_order = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___common_u1919)(tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___common_u1928)(tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ* dest_p0, tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___common_u1919((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(NI16, get_i16__common_u461)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NI16 result;
	NU16 T1_;
NIM_BOOL* nimErr_;
	nimfr_("get_i16", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result = (NI16)0;
	nimln_(422);
	T1_ = (NU16)0;
	T1_ = get_u16__common_u445(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI16) (T1_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, plus___common_u337)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ b_p1) {
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ result;
	NI16 colontmpD_;
	NI16 colontmpD__2;
	nimfr_("+", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	colontmpD_ = (NI16)0;
	colontmpD__2 = (NI16)0;
	nimln_(374);
	nimln_(373);
	nimln_(374);
	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	nimln_(375);
	colontmpD_ = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.x))) + (NU16)(((NU16) (b_p1.x))))));
	result.x = colontmpD_;
	nimln_(376);
	colontmpD__2 = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.y))) + (NU16)(((NU16) (b_p1.y))))));
	result.y = colontmpD__2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, get_seq_int__common_u523)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g result;
	NU16 len;
	NU16 j;
NIM_BOOL* nimErr_;
	nimfr_("get_seq_int", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(453);
	len = get_u16__common_u445(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(454);
	j = ((NU16)0);
	{
		nimln_(455);
		while (1) {
			NI T3_;
			if (!((NU16)(j) < (NU16)(len))) goto LA2;
			nimln_(456);
			T3_ = (NI)0;
			T3_ = get_int__common_u377(input_p0, i_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			add__common_u529((&result), T3_);
			nimln_(457);
			j += ((NI)1);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_29;
	NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_30;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_29)) { raiseOverflow(); goto BeforeRet_;
	};
	(*(*s_p0).p).data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_29)] = 0;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_30)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_30);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, get_string__common_u558)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NimStringV2 result;
	NU16 len;
	NU16 j;
NIM_BOOL* nimErr_;
	nimfr_("get_string", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(460);
	len = get_u16__common_u445(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(461);
	j = ((NU16)0);
	{
		nimln_(462);
		while (1) {
			NU8 T3_;
			if (!((NU16)(j) < (NU16)(len))) goto LA2;
			nimln_(463);
			T3_ = (NU8)0;
			T3_ = get_u8__common_u465(input_p0, i_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimAddCharV1((&result), ((NIM_CHAR) (((NI) (T3_)))));
			nimln_(464);
			j += ((NI)1);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, get_point__common_u504)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ result;
NIM_BOOL* nimErr_;
	nimfr_("get_point", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	nimln_(436);
	nimln_(435);
	nimln_(436);
	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	nimln_(437);
	result.x = get_i16__common_u461(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(438);
	result.y = get_i16__common_u461(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, get_seq_u8__common_u508)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1, NIM_BOOL bits32_p2) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI len;
	NI j;
NIM_BOOL* nimErr_;
	nimfr_("get_seq_u8", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(442);
	len = ((NI)0);
	nimln_(443);
	{
		NU32 T5_;
		if (!bits32_p2) goto LA3_;
		nimln_(444);
		T5_ = (NU32)0;
		T5_ = get_u32__common_u421(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		len = ((NI) (T5_));
	}
	goto LA1_;
LA3_: ;
	{
		NU16 T7_;
		nimln_(446);
		T7_ = (NU16)0;
		T7_ = get_u16__common_u445(input_p0, i_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		len = ((NI) (T7_));
	}
LA1_: ;
	nimln_(447);
	j = ((NI)0);
	{
		nimln_(448);
		while (1) {
			NU8 T10_;
			NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_31;
			if (!(j < len)) goto LA9;
			nimln_(449);
			T10_ = (NU8)0;
			T10_ = get_u8__common_u465(input_p0, i_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			add__pureZtimes_u2492((&result), T10_);
			nimln_(450);
			if (nimAddInt(j, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_31)) { raiseOverflow(); goto BeforeRet_;
			};
			j = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_31);
		} LA9: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, get_u64__common_u417)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	NU64 result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("get_u64", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	nimln_(407);
	T1_ = (NI)0;
	T1_ = get_int__common_u377(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NU64) (T1_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw, get_sync_state__common_u481)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p0, NI* i_p1) {
	tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw result;
	NU8 T1_;
NIM_BOOL* nimErr_;
	nimfr_("get_sync_state", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw)0;
	nimln_(433);
	T1_ = (NU8)0;
	T1_ = get_u8__common_u465(input_p0, i_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((T1_) < ((tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw)0) || (T1_) > ((tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw)2)){ raiseRangeErrorI(T1_, ((tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw)0), ((tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw)2)); goto BeforeRet_;
	}
	result = ((tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw) (T1_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nim95save95monger_u662)(tyObject_parse_result__oALM4avZmHBnEv9bFJW9bLYA* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___versionsZv48_u475((*dest_p0).components);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___versionsZv48_u635((*dest_p0).wires);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((*dest_p0).hub_description.p && !((*dest_p0).hub_description.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).hub_description.p);
}
	eqdestroy___common_u846((*dest_p0).dependencies);
	if ((*dest_p0).description.p && !((*dest_p0).description.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).description.p);
}
	eqdestroy___pureZtimes_u2534((*dest_p0).player_data);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___versionsZv48_u298)(tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* dest_p0, tyObject_parse_component__Q3n04UtX2pKCJzom9csVP2g* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	(*dest_p0).kind = (*src_p1).kind;
	(*dest_p0).position.x = (*src_p1).position.x;
	(*dest_p0).position.y = (*src_p1).position.y;
	(*dest_p0).custom_displacement.x = (*src_p1).custom_displacement.x;
	(*dest_p0).custom_displacement.y = (*src_p1).custom_displacement.y;
	(*dest_p0).rotation = (*src_p1).rotation;
	(*dest_p0).real_offset = (*src_p1).real_offset;
	(*dest_p0).permanent_id = (*src_p1).permanent_id;
	if ((*dest_p0).custom_string.p != (*src_p1).custom_string.p) {	if ((*dest_p0).custom_string.p && !((*dest_p0).custom_string.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).custom_string.p);
}
	}
(*dest_p0).custom_string.len = (*src_p1).custom_string.len; (*dest_p0).custom_string.p = (*src_p1).custom_string.p;
	(*dest_p0).custom_id = (*src_p1).custom_id;
	(*dest_p0).setting1 = (*src_p1).setting1;
	(*dest_p0).setting2 = (*src_p1).setting2;
	if ((*dest_p0).selected_programs.data.p != (*src_p1).selected_programs.data.p) {	eqdestroy___common_u1527((*dest_p0).selected_programs.data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
(*dest_p0).selected_programs.data.len = (*src_p1).selected_programs.data.len; (*dest_p0).selected_programs.data.p = (*src_p1).selected_programs.data.p;
	(*dest_p0).selected_programs.counter = (*src_p1).selected_programs.counter;
	(*dest_p0).ui_order = (*src_p1).ui_order;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___versionsZv48_u445)(tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* dest_p0) {
	eqdestroy___common_u1919((*dest_p0).path);
	if ((*dest_p0).comment.p && !((*dest_p0).comment.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).comment.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___versionsZv48_u442)(tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* dest_p0) {
	(*dest_p0).path.len = 0; (*dest_p0).path.p = NIM_NIL;
	(*dest_p0).kind = 0;
	(*dest_p0).color = 0;
	(*dest_p0).comment.len = 0; (*dest_p0).comment.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___versionsZv48_u454)(tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* dest_p0, tyObject_parse_wire__7xYntS12s4Pztihy9a5PR7A* src_p1) {
	if ((*dest_p0).path.p != (*src_p1).path.p) {	eqdestroy___common_u1919((*dest_p0).path);
	}
(*dest_p0).path.len = (*src_p1).path.len; (*dest_p0).path.p = (*src_p1).path.p;
	(*dest_p0).kind = (*src_p1).kind;
	(*dest_p0).color = (*src_p1).color;
	if ((*dest_p0).comment.p != (*src_p1).comment.p) {	if ((*dest_p0).comment.p && !((*dest_p0).comment.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).comment.p);
}
	}
(*dest_p0).comment.len = (*src_p1).comment.len; (*dest_p0).comment.p = (*src_p1).comment.p;
}
N_LIB_PRIVATE N_NIMCALL(void, add_int__common_u575)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NI input_p1) {
	NU8 colontmpD_;
	NU8 colontmpD__2;
	NU8 colontmpD__3;
	NU8 colontmpD__4;
	NU8 colontmpD__5;
	NU8 colontmpD__6;
	NU8 colontmpD__7;
	NU8 colontmpD__8;
	nimfr_("add_int", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	colontmpD__3 = (NU8)0;
	colontmpD__4 = (NU8)0;
	colontmpD__5 = (NU8)0;
	colontmpD__6 = (NU8)0;
	colontmpD__7 = (NU8)0;
	colontmpD__8 = (NU8)0;
	nimln_(470);
	colontmpD_ = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)0))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	nimln_(471);
	colontmpD__2 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)8))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__2);
	nimln_(472);
	colontmpD__3 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)16))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__3);
	nimln_(473);
	colontmpD__4 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)24))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__4);
	nimln_(474);
	colontmpD__5 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)32))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__5);
	nimln_(475);
	colontmpD__6 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)40))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__6);
	nimln_(476);
	colontmpD__7 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)48))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__7);
	nimln_(477);
	colontmpD__8 = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)56))) & ((NI)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__8);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_u32__common_u645)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU32 input_p1) {
	NU8 colontmpD_;
	NU8 colontmpD__2;
	NU8 colontmpD__3;
	NU8 colontmpD__4;
	nimfr_("add_u32", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	colontmpD__3 = (NU8)0;
	colontmpD__4 = (NU8)0;
	nimln_(483);
	colontmpD_ = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)0))) & ((NU32)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	nimln_(484);
	colontmpD__2 = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)8))) & ((NU32)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__2);
	nimln_(485);
	colontmpD__3 = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)16))) & ((NU32)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__3);
	nimln_(486);
	colontmpD__4 = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)24))) & ((NU32)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__4);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_bool__common_u568)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NIM_BOOL input_p1) {
	NIM_BOOL colontmpD_;
	nimfr_("add_bool", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NIM_BOOL)0;
	nimln_(467);
	colontmpD_ = input_p1;
	add__pureZtimes_u2492((&(*arr_p0)), ((NU8) (colontmpD_)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_u16__common_u680)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU16 input_p1) {
	NU8 colontmpD_;
	NU8 colontmpD__2;
	nimfr_("add_u16", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	nimln_(489);
	colontmpD_ = ((NU8) ((NU16)((NU16)((NU16)(input_p1) >> (NU64)(((NI)0))) & ((NU16)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	nimln_(490);
	colontmpD__2 = ((NU8) ((NU16)((NU16)((NU16)(input_p1) >> (NU64)(((NI)8))) & ((NU16)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_seq_int__common_u815)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g input_p1) {
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("add_seq_int", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(524);
	T1_ = input_p1.len;
	add_u16__common_u680(arr_p0, ((NU16) (T1_)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI* i;
		NI i_2;
		NI L;
		NI T3_;
		i = (NI*)0;
		nimlf_(241, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i_2 = ((NI)0);
		nimln_(242);
		T3_ = input_p1.len;
		L = T3_;
		{
			nimln_(243);
			while (1) {
				NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_32;
				if (!(i_2 < L)) goto LA5;
				nimlf_(525, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
				if (i_2 < 0 || i_2 >= input_p1.len){ raiseIndexError2(i_2,input_p1.len-1); goto BeforeRet_;
				}
				i = (&input_p1.p->data[i_2]);
				add_int__common_u575(arr_p0, (*i));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(245, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				if (nimAddInt(i_2, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_32)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_32);
				nimln_(246);
				{
					NI T8_;
					T8_ = input_p1.len;
					if (!!((T8_ == L))) goto LA9_;
					failedAssertImpl__stdZassertions_u310(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_34);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA9_: ;
			} LA5: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_u8__common_u718)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU8 input_p1) {
	NU8 colontmpD_;
	nimfr_("add_u8", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	nimln_(497);
	colontmpD_ = input_p1;
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_string__common_u1169)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NimStringV2 input_p1) {
NIM_BOOL* nimErr_;
	nimfr_("add_string", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(534);
	add_u16__common_u680(arr_p0, ((NU16) (input_p1.len)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimlf_(259, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i = ((NI)0);
		nimln_(260);
		L = input_p1.len;
		{
			nimln_(261);
			while (1) {
				NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_35;
				if (!(i < L)) goto LA3;
				nimlf_(535, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
				if (i < 0 || i >= input_p1.len){ raiseIndexError2(i,input_p1.len-1); goto BeforeRet_;
				}
				c = input_p1.p->data[i];
				nimln_(536);
				nimln_(535);
				add_u8__common_u718(arr_p0, ((NU8) (((NU8)(c)))));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(263, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				if (nimAddInt(i, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_35)) { raiseOverflow(); goto BeforeRet_;
				};
				i = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_35);
				nimln_(264);
				{
					if (!!((input_p1.len == L))) goto LA6_;
					failedAssertImpl__stdZassertions_u310(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_37);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA6_: ;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_i16__common_u699)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NI16 input_p1) {
	NU8 colontmpD_;
	NU8 colontmpD__2;
	nimfr_("add_i16", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	nimln_(493);
	colontmpD_ = ((NU8) ((NI16)((NI16)((NI64)(input_p1) >> (NU64)(((NI)0))) & ((NI16)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	nimln_(494);
	colontmpD__2 = ((NU8) ((NI16)((NI16)((NI64)(input_p1) >> (NU64)(((NI)8))) & ((NI16)255))));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD__2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_point__common_u761)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ input_p1) {
NIM_BOOL* nimErr_;
	nimfr_("add_point", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(512);
	add_i16__common_u699(arr_p0, input_p1.x);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(513);
	add_i16__common_u699(arr_p0, input_p1.y);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_sync_state__common_u750)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tyEnum_sync_state__tvxHcqa5v8SJ9cNC3ZFADOw input_p1) {
	NU8 colontmpD_;
	nimfr_("add_sync_state", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	nimln_(509);
	colontmpD_ = ((NU8) (input_p1));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_seq_u8__common_u764)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ input_p1, NIM_BOOL bits32_p2) {
NIM_BOOL* nimErr_;
	nimfr_("add_seq_u8", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(516);
	{
		NI T5_;
		if (!bits32_p2) goto LA3_;
		nimln_(517);
		T5_ = input_p1.len;
		add_u32__common_u645(arr_p0, ((NU32) (T5_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NI T7_;
		nimln_(519);
		T7_ = input_p1.len;
		add_u16__common_u680(arr_p0, ((NU16) (T7_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	{
		NU8* i;
		NI i_2;
		NI L;
		NI T9_;
		i = (NU8*)0;
		nimlf_(241, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i_2 = ((NI)0);
		nimln_(242);
		T9_ = input_p1.len;
		L = T9_;
		{
			nimln_(243);
			while (1) {
				NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_38;
				if (!(i_2 < L)) goto LA11;
				nimlf_(520, "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
				if (i_2 < 0 || i_2 >= input_p1.len){ raiseIndexError2(i_2,input_p1.len-1); goto BeforeRet_;
				}
				i = (&input_p1.p->data[i_2]);
				add_u8__common_u718(arr_p0, (*i));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(245, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				if (nimAddInt(i_2, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_38)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_38);
				nimln_(246);
				{
					NI T14_;
					T14_ = input_p1.len;
					if (!!((T14_ == L))) goto LA15_;
					failedAssertImpl__stdZassertions_u310(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_39);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA15_: ;
			} LA11: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_component_kind__common_u732)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tyEnum_component_kind__WIiWvJdYJHSN2YmZuM2gMQ input_p1) {
NIM_BOOL* nimErr_;
	nimfr_("add_component_kind", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(503);
	add_u16__common_u680(arr_p0, ((NU16) (input_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_u64__common_u642)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, NU64 input_p1) {
NIM_BOOL* nimErr_;
	nimfr_("add_u64", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(480);
	add_int__common_u575(arr_p0, ((NI) (input_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, add_wire_kind__common_u739)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tyEnum_wire_kind__HFpO3vcq9cZbElI9cZwZEl9bw input_p1) {
	NU8 colontmpD_;
	nimfr_("add_wire_kind", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
	colontmpD_ = (NU8)0;
	nimln_(506);
	colontmpD_ = ((NU8) (input_p1));
	add__pureZtimes_u2492((&(*arr_p0)), colontmpD_);
	popFrame();
}
static N_INLINE(NI, find__common_u1762)(tyArray__UfdIMDE1tgdULaKrSRVsiw a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ item_p1) {
	NI result;
	nimfr_("find", "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
{	result = (NI)0;
	nimln_(1665);
	result = ((NI)0);
	{
		tyObject_point__MN7UdrA9cGABfr4tCur5RbQ i;
		NI i_2;
		nimZeroMem((void*)(&i), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
		nimlf_(38, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
		i_2 = ((NI)0);
		{
			nimln_(39);
			while (1) {
				NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_40;
				NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_41;
				nimlf_(1666, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
				i = a_p0[(i_2)- 0];
				{
					NIM_BOOL T6_;
					nimln_(1667);
					T6_ = (NIM_BOOL)0;
					T6_ = eqeq___common_u1835(i, item_p1);
					if (!T6_) goto LA7_;
					goto BeforeRet_;
				}
LA7_: ;
				nimln_(1666);
				if (nimAddInt(result, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_40)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_40);
				nimlf_(41, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system\\iterators.nim");
				{
					if (!(((NI)7) <= ((NI) (i_2)))) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(42);
				if (nimAddInt(i_2, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_41)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__IYKT5L9bjnVwc9cm3VCRe7wQ_41 < 0 || TM__IYKT5L9bjnVwc9cm3VCRe7wQ_41 > 7){ raiseOverflow(); goto BeforeRet_;
				}
				i_2 = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_41);
			}
		} LA2: ;
	}
	nimlf_(1669, "C:\\Users\\MegaIng\\.choosenim\\toolchains\\nim-2.0.0\\lib\\system.nim");
	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ, minus___common_u361)(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ a_p0, tyObject_point__MN7UdrA9cGABfr4tCur5RbQ b_p1) {
	tyObject_point__MN7UdrA9cGABfr4tCur5RbQ result;
	NI16 colontmpD_;
	NI16 colontmpD__2;
	nimfr_("-", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	colontmpD_ = (NI16)0;
	colontmpD__2 = (NI16)0;
	nimln_(380);
	nimln_(379);
	nimln_(380);
	nimZeroMem((void*)(&result), sizeof(tyObject_point__MN7UdrA9cGABfr4tCur5RbQ));
	nimln_(381);
	colontmpD_ = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.x))) - (NU16)(((NU16) (b_p1.x))))));
	result.x = colontmpD_;
	nimln_(382);
	colontmpD__2 = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.y))) - (NU16)(((NU16) (b_p1.y))))));
	result.y = colontmpD__2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add_path__common_u1755)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* arr_p0, tySequence__IWp6HidcF2FZV9aE2TH9ap9bQ path_p1) {
	NI offset;
NIM_BOOL* nimErr_;
	nimfr_("add_path", "C:\\Users\\MegaIng\\PycharmProjects\\py_save_monger\\save_monger\\nim_save_monger\\common.nim");
{nimErr_ = nimErrorFlag();
	nimln_(552);
	if (((NI)0) < 0 || ((NI)0) >= path_p1.len){ raiseIndexError2(((NI)0),path_p1.len-1); goto BeforeRet_;
	}
	add_point__common_u761(arr_p0, path_p1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(554);
	offset = ((NI)0);
	{
		nimln_(556);
		while (1) {
			NI T3_;
			NI original_direction;
			NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42;
			tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T4_;
			NI max_length;
			NI T14_;
			NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_43;
			NI length;
			NI direction;
			NU8 segment;
			NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_48;
			T3_ = (path_p1.len-1);
			if (!(offset < T3_)) goto LA2;
			nimln_(557);
			if (nimAddInt(offset, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42) >= path_p1.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42),path_p1.len-1); goto BeforeRet_;
			}
			if (offset < 0 || offset >= path_p1.len){ raiseIndexError2(offset,path_p1.len-1); goto BeforeRet_;
			}
			T4_ = minus___common_u361(path_p1.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_42)], path_p1.p->data[offset]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			original_direction = find__common_u1762(DIRECTIONS__common_u278, T4_);
			nimln_(559);
			{
				if (!(original_direction == ((NI)-1))) goto LA7_;
				nimln_(560);
				{
					NI T11_;
					T11_ = path_p1.len;
					if (!(T11_ == ((NI)2))) goto LA12_;
					nimln_(562);
					add_u8__common_u718(arr_p0, ((NU8)32));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(563);
					if (((NI)1) < 0 || ((NI)1) >= path_p1.len){ raiseIndexError2(((NI)1),path_p1.len-1); goto BeforeRet_;
					}
					add_point__common_u761(arr_p0, path_p1.p->data[((NI)1)]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(564);
					goto BeforeRet_;
				}
LA12_: ;
				nimln_(565);
				goto LA1;
			}
LA7_: ;
			nimln_(568);
			T14_ = (path_p1.len-1);
			if (nimSubInt(T14_, offset, &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_43)) { raiseOverflow(); goto BeforeRet_;
			};
			max_length = (((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_43) <= ((NI)31)) ? (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_43) : ((NI)31));
			nimln_(569);
			length = ((NI)1);
			nimln_(570);
			direction = original_direction;
			{
				nimln_(572);
				while (1) {
					NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_44;
					NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45;
					NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46;
					tyObject_point__MN7UdrA9cGABfr4tCur5RbQ T17_;
					NI TM__IYKT5L9bjnVwc9cm3VCRe7wQ_47;
					if (!(length < max_length)) goto LA16;
					nimln_(573);
					if (nimAddInt(offset, length, &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_44)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_44), ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45) >= path_p1.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45),path_p1.len-1); goto BeforeRet_;
					}
					if (nimAddInt(offset, length, &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46) < 0 || (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46) >= path_p1.len){ raiseIndexError2((NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46),path_p1.len-1); goto BeforeRet_;
					}
					T17_ = minus___common_u361(path_p1.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_45)], path_p1.p->data[(NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_46)]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					direction = find__common_u1762(DIRECTIONS__common_u278, T17_);
					nimln_(574);
					{
						if (!!((direction == original_direction))) goto LA20_;
						goto LA15;
					}
LA20_: ;
					nimln_(575);
					if (nimAddInt(length, ((NI)1), &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_47)) { raiseOverflow(); goto BeforeRet_;
					};
					length = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_47);
				} LA16: ;
			} LA15: ;
			nimln_(577);
			segment = ((NU8) ((NI)((NI)((NU64)(original_direction) << (NU64)(((NI)5))) | length)));
			nimln_(578);
			add_u8__common_u718(arr_p0, segment);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(580);
			if (nimAddInt(offset, length, &TM__IYKT5L9bjnVwc9cm3VCRe7wQ_48)) { raiseOverflow(); goto BeforeRet_;
			};
			offset = (NI)(TM__IYKT5L9bjnVwc9cm3VCRe7wQ_48);
		} LA2: ;
	} LA1: ;
	nimln_(583);
	add_u8__common_u718(arr_p0, ((NU8)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
