from db_copilot.contract.llm_core import LLMType
from db_copilot.prompts.instruct.base import DEFAULT_INSTRUCT_TEMPLATE

INSTRUCT_TEMPLATES = {}

INSTRUCT_TEMPLATES[LLMType.GPT35_TURBO] = DEFAULT_INSTRUCT_TEMPLATE
INSTRUCT_TEMPLATES[LLMType.GPT4_DV3] = DEFAULT_INSTRUCT_TEMPLATE