
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-22T05:19:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "978fe388e99eae4dd672963764af72dcbd214646",
 "version": "1.28.1.post0.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
