# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.token_link_request_dto import TokenLinkRequestDto


class TestTokenLinkRequestDto(unittest.TestCase):
    """TokenLinkRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenLinkRequestDto:
        """Test TokenLinkRequestDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TokenLinkRequestDto`
        """
        model = TokenLinkRequestDto()
        if include_optional:
            return TokenLinkRequestDto(
                type = 'FUNGIBLE_TOKEN',
                ref_id = 'USDC_ETH_TEST5_1XF5',
                display_name = 'My Simple ERC20 Token'
            )
        else:
            return TokenLinkRequestDto(
                type = 'FUNGIBLE_TOKEN',
                ref_id = 'USDC_ETH_TEST5_1XF5',
        )
        """

    def testTokenLinkRequestDto(self):
        """Test TokenLinkRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
