
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-22T10:54:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "947fee036cab67cede0ce7e8bf2ddd66c7ff4e3c",
 "version": "2.41.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
