
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-21T17:21:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d34b41d4c133c478652979a31f49172e42baa89",
 "version": "2024.7.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
