# Generated by Django 4.2.11 on 2024-06-19 02:46
from pathlib import Path

from django.db import migrations

from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ("edc_qareports", "0008_qareportlogsummary"),
    ]

    operations = [
        migrations.RunSQL(
            read_unmanaged_model_sql(
                app_name="edc_qareports",
                fullpath=Path(__file__).parent.parent
                / "models"
                / "unmanaged"
                / "qa_report_log_summary.sql",
            )
        )
    ]
