# Generated by Django 4.2.11 on 2024-06-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_qareports", "0009_auto_20240619_0546"),
    ]

    operations = []
