
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-24T16:11:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "efbe3df4c5e7bcfef5462f8ca24cb7711b1ee17c",
 "version": "0.0.043500"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
