
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-25T09:18:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2ee406591a12bb1340a9579411cbc3bd87d5ca7",
 "version": "2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
